import type { Category } from './types'

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Food',
    type: 'expense',
    icon: '🍔',
    color: '#FF6347',
    slug: 'food',
  },
  {
    id: '2',
    name: 'Transport',
    type: 'expense',
    icon: '🚗',
    color: '#1E90FF',
    slug: 'transport',
  },
  {
    id: '3',
    name: 'Entertainment',
    type: 'expense',
    icon: '🎬',
    color: '#FFD700',
    slug: 'entertainment',
  },
  {
    id: '4',
    name: 'Salary',
    type: 'income',
    icon: '💼',
    color: '#32CD32',
    slug: 'salary',
  },
  {
    id: '5',
    name: 'Freelance',
    type: 'income',
    icon: '🖥️',
    color: '#8A2BE2',
    slug: 'freelance',
  },
  {
    id: '6',
    name: 'Health',
    type: 'expense',
    icon: '💊',
    color: '#FF69B4',
    slug: 'health',
  },
  {
    id: '7',
    name: 'Education',
    type: 'expense',
    icon: '📚',
    color: '#20B2AA',
    slug: 'education',
  },
  {
    id: '8',
    name: 'Investment',
    type: 'income',
    icon: '📈',
    color: '#FF4500',
    slug: 'investment',
  },
  {
    id: '9',
    name: 'Gifts',
    type: 'income',
    icon: '🎁',
    color: '#FF1493',
    slug: 'gifts',
  },
  {
    id: '10',
    name: 'Utilities',
    type: 'expense',
    icon: '💡',
    color: '#00CED1',
    slug: 'utilities',
  },
  {
    id: '11',
    name: 'Travel',
    type: 'expense',
    icon: '✈️',
    color: '#FF8C00',
    slug: 'travel',
  },
  {
    id: '12',
    name: 'Miscellaneous',
    type: 'expense',
    icon: '🛍️',
    color: '#A52A2A',
    slug: 'miscellaneous',
  },
  {
    id: '13',
    name: 'Bonus',
    type: 'income',
    icon: '🎉',
    color: '#32CD32',
    slug: 'bonus',
  },
  {
    id: '14',
    name: 'Rent',
    type: 'expense',
    icon: '🏠',
    color: '#8B4513',
    slug: 'rent',
  },
  {
    id: '15',
    name: 'Savings',
    type: 'income',
    icon: '💰',
    color: '#228B22',
    slug: 'savings',
  },
  {
    id: '16',
    name: 'Charity',
    type: 'expense',
    icon: '❤️',
    color: '#FF69B4',
    slug: 'charity',
  },
  {
    id: '17',
    name: 'Side hustle',
    type: 'income',
    icon: '🛠️',
    color: '#8A2BE2',
    slug: 'side-hustle',
  },
  {
    id: '18',
    name: 'Subscriptions',
    type: 'expense',
    icon: '📱',
    color: '#1E90FF',
    slug: 'subscriptions',
  },
  {
    id: '19',
    name: 'Other Income',
    type: 'income',
    icon: '💵',
    color: '#32CD32',
    slug: 'other-income',
  },
  {
    id: '20',
    name: 'Other Expense',
    type: 'expense',
    icon: '🛒',
    color: '#A52A2A',
    slug: 'other-expense',
  },
  {
    id: '21',
    name: 'Health Insurance',
    type: 'expense',
    icon: '🏥',
    color: '#FF69B4',
    slug: 'health-insurance',
  },
  {
    id: '22',
    name: 'Car Maintenance',
    type: 'expense',
    icon: '🔧',
    color: '#1E90FF',
    slug: 'car-maintenance',
  },
  {
    id: '23',
    name: 'Grocery',
    type: 'expense',
    icon: '🛒',
    color: '#FF6347',
    slug: 'grocery',
  },
  {
    id: '24',
    name: 'Dining Out',
    type: 'expense',
    icon: '🍽️',
    color: '#FFD700',
    slug: 'dining-out',
  },
]
