// Code generated by tools/sync-catalog/generate.mjs from tools/sync-catalog/manifest.json. DO NOT EDIT.

export type CatalogConflictTranslator = (key: string) => string

export type CatalogConflictEntity =
  | 'account'
  | 'category'
  | 'debtor'
  | 'debt_operation'
  | 'planned_payment'
  | 'transaction'

export function catalogConflictEntityLabel(
  t: CatalogConflictTranslator,
  entity: CatalogConflictEntity,
): string {
  switch (entity) {
    case 'account':
      return t('sync.conflicts.entity.account')
    case 'category':
      return t('sync.conflicts.entity.category')
    case 'debtor':
      return t('sync.conflicts.entity.debtor')
    case 'debt_operation':
      return t('sync.conflicts.entity.debt_operation')
    case 'planned_payment':
      return t('sync.conflicts.entity.planned_payment')
    case 'transaction':
      return t('sync.conflicts.entity.transaction')
  }
  return ''
}
