/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Регистрация пользователя
         * @description Создаёт пользователя и сразу стартует сессию (Set-Cookie).
         *
         *     Registration is not rate-limited (TODO). Login (see `loginUser`) carries
         *     the per-ClientIP failure rate limit and trusted-proxy policy.
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Вход
         * @description Проверяет credentials, стартует сессию.
         *
         *     ## Rate limiting & trusted proxies
         *
         *     Login is failure-rate-limited per **ClientIP**: after 5 failed attempts
         *     (401/403) within the lockout window (default 15m) the IP is blocked and
         *     returns `429` with a `Retry-After` header (seconds until unlock); a
         *     successful login resets the counter. The rate limiter keys on `ClientIP`,
         *     which is taken from the TCP `RemoteAddr` unless `trusted_proxies` is
         *     configured - by default `X-Forwarded-For`/`X-Real-IP` are **ignored**
         *     to prevent IP spoofing and lockout abuse
         *     (see go-chi/httprate advisory / GHSA-9g5q-2w5x-hmxf). Behind a known
         *     proxy/CDN, configure `trusted_proxies` so `ClientIP` resolves correctly.
         */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Выход
         * @description Удаляет текущую сессию на сервере и сбрасывает cookie. Если cookie
         *     отсутствует — молча возвращает 204.
         */
        post: operations["logoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список активных сессий
         * @description Возвращает активные (не истёкшие) сессии текущего user. Токены
         *     **не возвращаются** — только метаданные + `isCurrent`.
         */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        /**
         * Завершить все сессии, кроме текущей
         * @description Инвалидирует все сессии user, **кроме текущей** (остаёшься в системе
         *     на этом устройстве). Cookie текущей сессии не сбрасывается.
         */
        delete: operations["deleteAllSessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Подтвердить email одноразовым кодом
         * @description Проверяет 6-значный OTP-код текущего user. Brute-force защита: после
         *     MaxVerificationAttempts неверных попыток код инвалидирован; per-IP rate
         *     limit блокирует серию попыток (429).
         */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Запросить новый verification code
         * @description Ротация: старый код инвалидируется, создаётся новый. Throttle — не
         *     чаще раза в VerificationResendThrottle (60s), иначе 429 с Retry-After.
         */
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Запросить сброс пароля
         * @description Unauthenticated. Anti-enumeration: всегда 204, независимо от
         *     существования email. Если user существует и не throttled — issue'ится
         *     high-entropy reset token (magic link). Mailer-stub в dev.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Подтвердить сброс и задать новый пароль
         * @description Unauthenticated. Потребляет одноразовый reset token, меняет пароль,
         *     отзываются **все** сессии user. High-entropy token — не брутфорсится.
         */
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список транзакций (cursor pagination)
         * @description Возвращает страницу в порядке occurredAt DESC, id DESC. Листание через
         *     opaque cursor (nextCursor); page size через limit (default 50, max 100).
         */
        get: operations["listTransactions"];
        put?: never;
        /**
         * Создать транзакцию
         * @description Поддерживает идемпотентность. Если заголовок `Idempotency-Key`
         *     присутствует, повторный запрос с тем же ключом + тем же body
         *     возвращает закешированный ответ. Тот же ключ + другой body → `409`.
         */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        /** Получить транзакцию по ID */
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        /** Удалить транзакцию */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        /**
         * Частично обновить транзакцию
         * @description Все поля optional. Поле `type` менять нельзя — оно вычисляется из
         *     набора ссылок (cashflow vs transfer).
         */
        patch: operations["updateTransaction"];
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список счетов (с balance) */
        get: operations["listAccounts"];
        put?: never;
        /** Создать счёт */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сводка балансов + netWorth */
        get: operations["getAccountBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        /** Получить счёт по ID */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        /**
         * Удалить счёт
         * @description 409 если есть привязанные transactions.
         */
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        /** Обновить счёт (name, manualAdjustment) */
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список категорий */
        get: operations["listCategories"];
        put?: never;
        /** Создать категорию */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        /** Получить категорию по ID */
        get: operations["getCategory"];
        put?: never;
        post?: never;
        /**
         * Удалить категорию
         * @description 409 если есть привязанные transactions.
         */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        /** Обновить категорию */
        patch: operations["updateCategory"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** @description Подтверждён ли email. */
            emailVerified: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /**
         * @description Cashflow-транзакция (income/expense) содержит `accountId`+`categoryId`.
         *     Transfer содержит `fromAccountId`+`toAccountId`. Эти пары
         *     взаимоисключающие.
         */
        Transaction: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            /** @enum {string} */
            type: "income" | "expense" | "transfer";
            /**
             * Format: int64
             * @description Минорные единицы (divisor 100 для USD/EUR/RUB).
             */
            amount: number;
            description: string;
            /** Format: date-time */
            occurredAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: uuid */
            accountId?: string | null;
            /** Format: uuid */
            categoryId?: string | null;
            /** Format: uuid */
            fromAccountId?: string | null;
            /** Format: uuid */
            toAccountId?: string | null;
            /**
             * Format: int
             * @description Версия транзакции
             */
            version: number;
        };
        TransactionCreateRequest: {
            /** @enum {string} */
            type: "income" | "expense" | "transfer";
            /** Format: int64 */
            amount: number;
            /** @default  */
            description: string;
            /** Format: date-time */
            occurredAt: string;
            /**
             * Format: uuid
             * @description Required для income/expense. Forbidden для transfer.
             */
            accountId?: string;
            /**
             * Format: uuid
             * @description Required для income/expense. Forbidden для transfer.
             */
            categoryId?: string;
            /**
             * Format: uuid
             * @description Required для transfer. Forbidden для income/expense.
             */
            fromAccountId?: string;
            /**
             * Format: uuid
             * @description Required для transfer. Forbidden для income/expense.
             */
            toAccountId?: string;
        };
        /** @description Все поля кроме `version` optional. Поле `type` менять нельзя. */
        TransactionUpdateRequest: {
            /** Format: int */
            version: number;
            /** Format: int64 */
            amount?: number;
            description?: string;
            /** Format: date-time */
            occurredAt?: string;
            /** Format: uuid */
            accountId?: string;
            /** Format: uuid */
            categoryId?: string;
            /** Format: uuid */
            fromAccountId?: string;
            /** Format: uuid */
            toAccountId?: string;
        };
        ErrorResponse: {
            /**
             * @description Machine-readable error code.
             * @example VALIDATION_FAILED
             */
            code: string;
            /** @description Human-readable сообщение. */
            message: string;
        };
        /**
         * @description ErrorResponse extended with a list of per-field validation errors.
         *     `errors` is required so this schema is distinguishable from the plain
         *     `ErrorResponse` inside `oneOf`.
         */
        ValidationErrorResponse: components["schemas"]["ErrorResponse"] & {
            errors: components["schemas"]["FieldError"][];
        };
        FieldError: {
            field: string;
            message: string;
        };
        /** @description Метаданные сессии без токена. */
        SessionResponse: {
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description Грубый proxy последней активности (обновляется при sliding).
             */
            updatedAt: string;
            /** Format: date-time */
            expiresAt: string;
            isCurrent: boolean;
        };
        Account: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            name: string;
            /** @enum {string} */
            currency: "USD" | "EUR" | "RUB";
            /** Format: int64 */
            openingBalance: number;
            /** Format: int64 */
            manualAdjustment: number;
            /**
             * Format: int64
             * @description Вычисляется сервером (opening + manual + Σ transactions).
             */
            balance: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AccountBalance: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            name: string;
            /** @enum {string} */
            currency: "USD" | "EUR" | "RUB";
            /** Format: int64 */
            balance: number;
        };
        AccountBalancesResponse: {
            balances: components["schemas"]["AccountBalance"][];
            /** Format: int64 */
            netWorth: number;
        };
        AccountCreateRequest: {
            name: string;
            /** @enum {string} */
            currency: "USD" | "EUR" | "RUB";
            /** Format: int64 */
            openingBalance: number;
        };
        /** @description Все поля optional. */
        AccountUpdateRequest: {
            name?: string;
            /** Format: int64 */
            manualAdjustment?: number;
        };
        Category: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            name: string;
            /** @enum {string} */
            type: "income" | "expense";
            icon: string;
            color: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CategoryCreateRequest: {
            name: string;
            /** @enum {string} */
            type: "income" | "expense";
            icon: string;
            color: string;
        };
        /** @description Все поля optional. */
        CategoryUpdateRequest: {
            name?: string;
            /** @enum {string} */
            type?: "income" | "expense";
            icon?: string;
            color?: string;
        };
    };
    responses: {
        /** @description Не авторизован (нет валидной session cookie). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UNAUTHORIZED",
                 *       "message": "missing session cookie"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Внутренняя ошибка сервера. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "INTERNAL_ERROR",
                 *       "message": "internal server error"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Неверное тело запроса (validation failed). */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "VALIDATION_FAILED",
                 *       "message": "validation failed",
                 *       "errors": [
                 *         {
                 *           "field": "email",
                 *           "message": "email is required"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ValidationErrorResponse"];
            };
        };
        /** @description Транзакция не найдена (или чужая). */
        TransactionNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "TRANSACTION_NOT_FOUND",
                 *       "message": "transaction not found"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Конфликт в версии транзакции (optimistic concurrency). */
        TransactionVersionConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "TRANSACTION_VERSION_CONFLICT",
                 *       "message": "transaction version conflict"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Счёт не найден (или чужой). */
        AccountNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "ACCOUNT_NOT_FOUND",
                 *       "message": "account not found"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Категория не найдена (или чужая). */
        CategoryNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "CATEGORY_NOT_FOUND",
                 *       "message": "category not found"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Счёт имеет привязанные transactions, удаление невозможно. */
        AccountInUse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "ACCOUNT_IN_USE",
                 *       "message": "account has transactions and cannot be deleted"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Категория имеет привязанные transactions, удаление невозможно. */
        CategoryInUse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "CATEGORY_IN_USE",
                 *       "message": "category has transactions and cannot be deleted"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Категория с таким name уже есть у user. */
        CategoryAlreadyExists: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "CATEGORY_ALREADY_EXISTS",
                 *       "message": "category already exists"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        TransactionId: string;
        /**
         * @description Уникальный client-generated ключ (UUID recommended). Один ключ =
         *     один intent. Повтор того же запроса возвращает тот же ответ.
         */
        IdempotencyKey: string;
        AccountId: string;
        CategoryId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example user@example.com
                     */
                    email: string;
                    /**
                     * @description Plaintext (хешируется на сервере).
                     * @example strong-password
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Пользователь создан, сессия установлена. */
            201: {
                headers: {
                    /** @description session_id cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Email уже занят. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "USER_ALREADY_EXISTS",
                     *       "message": "user already exists"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Успешный вход, сессия установлена. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Неверный email или пароль. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "INVALID_CREDENTIALS",
                     *       "message": "invalid credentials"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Слишком неудачных попыток входа с этого IP. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "TOO_MANY_REQUESTS",
                     *       "message": "too many login attempts, please try again later"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logoutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный выход (или cookie уже отсутствовал). */
            204: {
                headers: {
                    /** @description session_id cookie с Max-Age=-1 (browser удалит). */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Текущий пользователь по session cookie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список сессий. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteAllSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Все прочие сессии отозваны. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 123456 */
                    code: string;
                };
            };
        };
        responses: {
            /** @description Email подтверждён. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Код истёк / нет активного кода. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неверный код (attempts остаются). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "INVALID_VERIFICATION_CODE",
                     *       "message": "invalid verification code"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Email уже подтверждён. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "EMAIL_ALREADY_VERIFIED",
                     *       "message": "email already verified"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Brute-force lockout (per-IP). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "TOO_MANY_REQUESTS",
                     *       "message": "too many failed attempts, please try again later"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Новый код создан и "отправлен" (mailer-stub в dev). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email уже подтверждён. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "EMAIL_ALREADY_VERIFIED",
                     *       "message": "email already verified"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Throttle. */
            429: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "TOO_MANY_REQUESTS",
                     *       "message": "please wait before requesting a new code"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Всегда (anti-enumeration). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 256-bit hex token из reset-ссылки. */
                    token: string;
                    newPassword: string;
                };
            };
        };
        responses: {
            /** @description Пароль изменён, все сессии отозваны. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Невалидный/истёкший token или validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"] | components["schemas"]["ValidationErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                type?: "income" | "expense" | "transfer";
                accountId?: string;
                categoryId?: string;
                /** @description ISO date (YYYY-MM-DD), lower bound inclusive. */
                fromDate?: string;
                /** @description ISO date (YYYY-MM-DD), upper bound inclusive. */
                toDate?: string;
                /** @description Page size (default 50, max 100). */
                limit?: number;
                /** @description Opaque курсор из nextCursor предыдущего ответа. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница транзакций + курсор следующей страницы. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        transactions: components["schemas"]["Transaction"][];
                        /** @description Opaque курсор; null если страниц больше нет. */
                        nextCursor: string | null;
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Уникальный client-generated ключ (UUID recommended). Один ключ =
                 *     один intent. Повтор того же запроса возвращает тот же ответ.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreateRequest"];
            };
        };
        responses: {
            /** @description Транзакция создана. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            /**
             * @description Idempotency конфликт:
             *     - тот же ключ + другой body (mismatch)
             *     - тот же ключ пока предыдущий запрос ещё в полёте (pending)
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Бизнес-правило нарушено — ссылки не найдены или type-mismatch. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Транзакция. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["TransactionNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалено. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["TransactionNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionUpdateRequest"];
            };
        };
        responses: {
            /** @description Обновлённая транзакция. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Либо validation failed, либо пустой body (`no fields to update`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"] | components["schemas"]["ValidationErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["TransactionNotFound"];
            409: components["responses"]["TransactionVersionConflict"];
            /** @description То же, что у POST (бизнес-правило нарушено). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Счета текущего user с вычисленным balance. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreateRequest"];
            };
        };
        responses: {
            /** @description Счёт создан. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getAccountBalances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Балансы всех счетов и net worth. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountBalancesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Счёт. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["AccountNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалено. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["AccountNotFound"];
            409: components["responses"]["AccountInUse"];
            500: components["responses"]["InternalError"];
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdateRequest"];
            };
        };
        responses: {
            /** @description Обновлённый счёт. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["AccountNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listCategories: {
        parameters: {
            query?: {
                type?: "income" | "expense";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Категории текущего user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreateRequest"];
            };
        };
        responses: {
            /** @description Категория создана. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["CategoryAlreadyExists"];
            500: components["responses"]["InternalError"];
        };
    };
    getCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Категория. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["CategoryNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалено. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["CategoryNotFound"];
            409: components["responses"]["CategoryInUse"];
            500: components["responses"]["InternalError"];
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdateRequest"];
            };
        };
        responses: {
            /** @description Обновлённая категория. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["CategoryNotFound"];
            409: components["responses"]["CategoryAlreadyExists"];
            500: components["responses"]["InternalError"];
        };
    };
}
