// Code generated by tools/sync-catalog/generate.mjs from tools/sync-catalog/manifest.json. DO NOT EDIT.

package service

import "github.com/yurifa/expense-tracker-api/internal/domain"

var catalogBackedSyncEntities = map[string]struct{}{
	domain.SyncEntityAccount:        {},
	domain.SyncEntityCategory:       {},
	domain.SyncEntityDebtor:         {},
	domain.SyncEntityDebtOperation:  {},
	domain.SyncEntityPlannedPayment: {},
	domain.SyncEntityTransaction:    {},
}

func isCatalogBackedSyncEntity(entity string) bool {
	_, ok := catalogBackedSyncEntities[entity]
	return ok
}

func catalogSyncEntityLabel(entity string) string {
	switch entity {
	case domain.SyncEntityAccount:
		return "account"
	case domain.SyncEntityCategory:
		return "category"
	case domain.SyncEntityDebtor:
		return "debtor"
	case domain.SyncEntityDebtOperation:
		return "debt operation"
	case domain.SyncEntityPlannedPayment:
		return "planned payment"
	case domain.SyncEntityTransaction:
		return "transaction"
	default:
		return ""
	}
}

func catalogSyncEntityInvalidDataMessage(entity string) string {
	switch entity {
	case domain.SyncEntityAccount:
		return "invalid account data"
	case domain.SyncEntityCategory:
		return "invalid category data"
	case domain.SyncEntityDebtor:
		return "invalid debtor data"
	case domain.SyncEntityDebtOperation:
		return "invalid debt operation data"
	case domain.SyncEntityPlannedPayment:
		return "invalid planned payment data"
	case domain.SyncEntityTransaction:
		return "invalid transaction data"
	default:
		return ""
	}
}
