import type { Category } from './types'
import i18n from '@/app/i18n'

export const getDefaultCategories = (): Category[] => {
  const { t } = i18n.global

  return [
    {
      id: '1',
      name: t('seeds.categories.food'),
      type: 'expense',
      icon: '🍔',
      color: '#FF6347',
    },
    {
      id: '2',
      name: t('seeds.categories.transport'),
      type: 'expense',
      icon: '🚗',
      color: '#1E90FF',
    },
    {
      id: '3',
      name: t('seeds.categories.entertainment'),
      type: 'expense',
      icon: '🎬',
      color: '#FFD700',
    },
    {
      id: '4',
      name: t('seeds.categories.salary'),
      type: 'income',
      icon: '💼',
      color: '#32CD32',
    },
    {
      id: '5',
      name: t('seeds.categories.freelance'),
      type: 'income',
      icon: '🖥️',
      color: '#8A2BE2',
    },
    {
      id: '6',
      name: t('seeds.categories.health'),
      type: 'expense',
      icon: '💊',
      color: '#FF69B4',
    },
    {
      id: '7',
      name: t('seeds.categories.education'),
      type: 'expense',
      icon: '📚',
      color: '#20B2AA',
    },
    {
      id: '8',
      name: t('seeds.categories.investment'),
      type: 'income',
      icon: '📈',
      color: '#FF4500',
    },
    {
      id: '9',
      name: t('seeds.categories.gifts'),
      type: 'income',
      icon: '🎁',
      color: '#FF1493',
    },
    {
      id: '10',
      name: t('seeds.categories.utilities'),
      type: 'expense',
      icon: '💡',
      color: '#00CED1',
    },
    {
      id: '11',
      name: t('seeds.categories.travel'),
      type: 'expense',
      icon: '✈️',
      color: '#FF8C00',
    },
    {
      id: '12',
      name: t('seeds.categories.miscellaneous'),
      type: 'expense',
      icon: '🛍️',
      color: '#A52A2A',
    },
    {
      id: '13',
      name: t('seeds.categories.bonus'),
      type: 'income',
      icon: '🎉',
      color: '#32CD32',
    },
    {
      id: '14',
      name: t('seeds.categories.rent'),
      type: 'expense',
      icon: '🏠',
      color: '#8B4513',
    },
    {
      id: '15',
      name: t('seeds.categories.savings'),
      type: 'income',
      icon: '💰',
      color: '#228B22',
    },
    {
      id: '16',
      name: t('seeds.categories.charity'),
      type: 'expense',
      icon: '❤️',
      color: '#FF69B4',
    },
    {
      id: '17',
      name: t('seeds.categories.sideHustle'),
      type: 'income',
      icon: '🛠️',
      color: '#8A2BE2',
    },
    {
      id: '18',
      name: t('seeds.categories.subscriptions'),
      type: 'expense',
      icon: '📱',
      color: '#1E90FF',
    },
    {
      id: '19',
      name: t('seeds.categories.otherIncome'),
      type: 'income',
      icon: '💵',
      color: '#32CD32',
    },
    {
      id: '20',
      name: t('seeds.categories.otherExpense'),
      type: 'expense',
      icon: '🛒',
      color: '#A52A2A',
    },
    {
      id: '21',
      name: t('seeds.categories.healthInsurance'),
      type: 'expense',
      icon: '🏥',
      color: '#FF69B4',
    },
    {
      id: '22',
      name: t('seeds.categories.carMaintenance'),
      type: 'expense',
      icon: '🔧',
      color: '#1E90FF',
    },
    {
      id: '23',
      name: t('seeds.categories.grocery'),
      type: 'expense',
      icon: '🛒',
      color: '#FF6347',
    },
    {
      id: '24',
      name: t('seeds.categories.diningOut'),
      type: 'expense',
      icon: '🍽️',
      color: '#FFD700',
    },
  ]
}
