// Code generated by tools/sync-catalog/generate.mjs from tools/sync-catalog/manifest.json. DO NOT EDIT.

export type CatalogConflictEntity =
  | 'account'
  | 'category'
  | 'debtor'
  | 'debt_operation'
  | 'planned_payment'
  | 'transaction'

export function catalogConflictEntityLabel(entity: CatalogConflictEntity): string {
  switch (entity) {
    case 'account':
      return 'Счёт'
    case 'category':
      return 'Категория'
    case 'debtor':
      return 'Должник'
    case 'debt_operation':
      return 'Долговая операция'
    case 'planned_payment':
      return 'Плановый платёж'
    case 'transaction':
      return 'Транзакция'
  }
  return ''
}
