/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Регистрация пользователя
         * @description Создаёт пользователя и сразу стартует сессию (Set-Cookie).
         *
         *     Registration is not rate-limited (TODO). Login (see `loginUser`) carries
         *     the per-ClientIP failure rate limit and trusted-proxy policy.
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Вход
         * @description Проверяет credentials, стартует сессию.
         *
         *     ## Rate limiting & trusted proxies
         *
         *     Login is failure-rate-limited per **ClientIP**: after 5 failed attempts
         *     (401/403) within the lockout window (default 15m) the IP is blocked and
         *     returns `429` with a `Retry-After` header (seconds until unlock); a
         *     successful login resets the counter. The rate limiter keys on `ClientIP`,
         *     which is taken from the TCP `RemoteAddr` unless `trusted_proxies` is
         *     configured - by default `X-Forwarded-For`/`X-Real-IP` are **ignored**
         *     to prevent IP spoofing and lockout abuse
         *     (see go-chi/httprate advisory / GHSA-9g5q-2w5x-hmxf). Behind a known
         *     proxy/CDN, configure `trusted_proxies` so `ClientIP` resolves correctly.
         */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Выход
         * @description Удаляет текущую сессию на сервере и сбрасывает cookie. Если cookie
         *     отсутствует — молча возвращает 204.
         */
        post: operations["logoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список активных сессий
         * @description Возвращает активные (не истёкшие) сессии текущего user. Токены
         *     **не возвращаются** — только метаданные + `isCurrent`.
         */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        /**
         * Завершить все сессии, кроме текущей
         * @description Инвалидирует все сессии user, **кроме текущей** (остаёшься в системе
         *     на этом устройстве). Cookie текущей сессии не сбрасывается.
         */
        delete: operations["deleteAllSessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Подтвердить email одноразовым кодом
         * @description Проверяет 6-значный OTP-код текущего user. Brute-force защита: после
         *     MaxVerificationAttempts неверных попыток код инвалидирован; per-IP rate
         *     limit блокирует серию попыток (429).
         */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Запросить новый verification code
         * @description Ротация: старый код инвалидируется, создаётся новый. Throttle — не
         *     чаще раза в VerificationResendThrottle (60s), иначе 429 с Retry-After.
         */
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Запросить сброс пароля
         * @description Unauthenticated. Anti-enumeration: всегда 204, независимо от
         *     существования email. Если user существует и не throttled — issue'ится
         *     high-entropy reset token (magic link). Mailer-stub в dev.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Подтвердить сброс и задать новый пароль
         * @description Unauthenticated. Потребляет одноразовый reset token, меняет пароль,
         *     отзываются **все** сессии user. High-entropy token — не брутфорсится.
         */
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список транзакций (cursor pagination)
         * @description Возвращает страницу не удалённых (не tombstoned) транзакций в порядке
         *     occurredAt DESC, id DESC. Листание через opaque cursor (nextCursor);
         *     page size через limit (default 50, max 100).
         */
        get: operations["listTransactions"];
        put?: never;
        /**
         * Создать транзакцию
         * @description Поддерживает идемпотентность. Если заголовок `Idempotency-Key`
         *     присутствует, повторный запрос с тем же ключом + тем же body
         *     возвращает закешированный ответ. Тот же ключ + другой body → `409`.
         */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        /** Получить транзакцию по ID */
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        /**
         * Удалить транзакцию
         * @description Удаление мягкое (tombstone): транзакция исчезает из листингов и
         *     перестаёт влиять на балансы, но сохраняется для синхронизации
         *     устройств.
         */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        /**
         * Частично обновить транзакцию
         * @description Все поля optional. Поле `type` менять нельзя — оно вычисляется из
         *     набора ссылок (cashflow vs transfer).
         */
        patch: operations["updateTransaction"];
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список счетов (с balance)
         * @description Все не удалённые (не tombstoned) счета текущего user.
         */
        get: operations["listAccounts"];
        put?: never;
        /** Создать счёт */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сводка балансов + netWorth */
        get: operations["getAccountBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        /** Получить счёт по ID */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        /**
         * Удалить счёт
         * @description 409 если есть привязанные transactions. Удаление мягкое (tombstone):
         *     счёт исчезает из листингов, сводки балансов и net worth, но сохраняется
         *     для синхронизации устройств.
         */
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        /** Обновить счёт (name, manualAdjustment) */
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список категорий
         * @description Все не удалённые (не tombstoned) категории текущего user.
         */
        get: operations["listCategories"];
        put?: never;
        /** Создать категорию */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        /** Получить категорию по ID */
        get: operations["getCategory"];
        put?: never;
        post?: never;
        /**
         * Удалить категорию
         * @description 409 если есть привязанные transactions. Удаление мягкое (tombstone):
         *     категория исчезает из листингов, но сохраняется для синхронизации
         *     устройств.
         */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        /** Обновить категорию */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/api/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push пакета клиентских операций
         * @description Применяет пакет операций offline-first клиента. Каждая операция
         *     обрабатывается независимо (частичный успех не откатывает применённые
         *     элементы) и получает свой результат:
         *
         *     - `applied` — операция применена, `version` = новая серверная версия
         *       записи;
         *     - `conflict` — CAS-конфликт (`SYNC_VERSION_CONFLICT` при несовпадении
         *       `baseVersion`, `SYNC_ALREADY_EXISTS` когда запись с таким id уже
         *       существует и пришёл другой `opId`, `SYNC_DELETED_CONFLICT` когда
         *       запись на сервере удалена), `serverState` = текущее состояние записи;
         *     - `error` — нарушение бизнес-правил (например `CATEGORY_IN_USE`,
         *       `INVALID_REFS`, `CATEGORY_ALREADY_EXISTS`).
         *
         *     Идемпотентность постоянна: повторная доставка уже применённого `opId`
         *     (в том числе в другом батче/сессии) возвращает сохранённый результат
         *     без побочных эффектов. Update применяется только если текущая версия
         *     записи на сервере равна `baseVersion`. Create (`baseVersion = 0`):
         *     записи нет → создать; есть + тот же `opId` → replay сохранённого
         *     результата; есть + другой `opId` → `SYNC_ALREADY_EXISTS` без
         *     перезаписи. Delete уже удалённой записи идемпотентен (`applied`).
         */
        post: operations["syncPush"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Инкрементальный pull изменений по курсору
         * @description Возвращает изменения user из change-log с `seq` строго больше
         *     `cursor`, в порядке `seq` (upsert + tombstone, с серверной `version`
         *     каждой записи), плюс `nextCursor` — курсор следующей страницы или
         *     `null`, когда клиент догнал сервер. Пагинация через `limit`; клиент
         *     продолжает с сохранённого курсора ровно с того места, где остановился.
         */
        get: operations["syncPull"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** @description Подтверждён ли email. */
            emailVerified: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /**
         * @description Cashflow-транзакция (income/expense) содержит `accountId`+`categoryId`.
         *     Transfer содержит `fromAccountId`+`toAccountId`. Эти пары
         *     взаимоисключающие.
         */
        Transaction: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            /** @enum {string} */
            type: "income" | "expense" | "transfer";
            /**
             * Format: int64
             * @description Минорные единицы (divisor 100 для USD/EUR/RUB).
             */
            amount: number;
            description: string;
            /** Format: date-time */
            occurredAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: uuid */
            accountId?: string | null;
            /** Format: uuid */
            categoryId?: string | null;
            /** Format: uuid */
            fromAccountId?: string | null;
            /** Format: uuid */
            toAccountId?: string | null;
            /**
             * Format: int
             * @description Версия транзакции
             */
            version: number;
        };
        TransactionCreateRequest: {
            /**
             * Format: uuid
             * @description Опциональный клиентский id (UUID v4): offline-first клиенты
             *     генерируют его локально, сервер использует его как id записи.
             *     Дубликат для user → 409 `TRANSACTION_ALREADY_EXISTS`.
             */
            id?: string;
            /** @enum {string} */
            type: "income" | "expense" | "transfer";
            /** Format: int64 */
            amount: number;
            /** @default  */
            description: string;
            /** Format: date-time */
            occurredAt: string;
            /**
             * Format: uuid
             * @description Required для income/expense. Forbidden для transfer.
             */
            accountId?: string;
            /**
             * Format: uuid
             * @description Required для income/expense. Forbidden для transfer.
             */
            categoryId?: string;
            /**
             * Format: uuid
             * @description Required для transfer. Forbidden для income/expense.
             */
            fromAccountId?: string;
            /**
             * Format: uuid
             * @description Required для transfer. Forbidden для income/expense.
             */
            toAccountId?: string;
        };
        /** @description Все поля кроме `version` optional. Поле `type` менять нельзя. */
        TransactionUpdateRequest: {
            /** Format: int */
            version: number;
            /** Format: int64 */
            amount?: number;
            description?: string;
            /** Format: date-time */
            occurredAt?: string;
            /** Format: uuid */
            accountId?: string;
            /** Format: uuid */
            categoryId?: string;
            /** Format: uuid */
            fromAccountId?: string;
            /** Format: uuid */
            toAccountId?: string;
        };
        ErrorResponse: {
            /**
             * @description Machine-readable error code.
             * @example VALIDATION_FAILED
             */
            code: string;
            /** @description Human-readable сообщение. */
            message: string;
        };
        /** @description Метаданные сессии без токена. */
        SessionResponse: {
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description Грубый proxy последней активности (обновляется при sliding).
             */
            updatedAt: string;
            /** Format: date-time */
            expiresAt: string;
            isCurrent: boolean;
        };
        Account: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            name: string;
            /** @enum {string} */
            currency: "USD" | "EUR" | "RUB";
            /** Format: int64 */
            openingBalance: number;
            /** Format: int64 */
            manualAdjustment: number;
            /**
             * Format: int64
             * @description Вычисляется сервером (opening + manual + Σ transactions).
             */
            balance: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * Format: int
             * @description Версия счёта (optimistic concurrency).
             */
            version: number;
        };
        AccountBalance: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            name: string;
            /** @enum {string} */
            currency: "USD" | "EUR" | "RUB";
            /** Format: int64 */
            balance: number;
        };
        AccountBalancesResponse: {
            balances: components["schemas"]["AccountBalance"][];
            /** Format: int64 */
            netWorth: number;
        };
        AccountCreateRequest: {
            /**
             * Format: uuid
             * @description Опциональный клиентский id (UUID v4). Дубликат для user →
             *     409 `ACCOUNT_ALREADY_EXISTS`.
             */
            id?: string;
            name: string;
            /** @enum {string} */
            currency: "USD" | "EUR" | "RUB";
            /** Format: int64 */
            openingBalance: number;
        };
        /**
         * @description Все поля кроме `version` optional. `version` — optimistic concurrency
         *     (аналогично транзакциям): при параллельном изменении → 409
         *     `ACCOUNT_VERSION_CONFLICT`.
         */
        AccountUpdateRequest: {
            /** Format: int */
            version: number;
            name?: string;
            /** Format: int64 */
            manualAdjustment?: number;
        };
        Category: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            name: string;
            /** @enum {string} */
            type: "income" | "expense";
            icon: string;
            color: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * Format: int
             * @description Версия категории (optimistic concurrency).
             */
            version: number;
        };
        CategoryCreateRequest: {
            /**
             * Format: uuid
             * @description Опциональный клиентский id (UUID v4). Дубликат для user →
             *     409 `CATEGORY_ALREADY_EXISTS`.
             */
            id?: string;
            name: string;
            /** @enum {string} */
            type: "income" | "expense";
            icon: string;
            color: string;
        };
        /**
         * @description Все поля кроме `version` optional. `version` — optimistic concurrency:
         *     при параллельном изменении → 409 `CATEGORY_VERSION_CONFLICT`.
         */
        CategoryUpdateRequest: {
            /** Format: int */
            version: number;
            name?: string;
            /** @enum {string} */
            type?: "income" | "expense";
            icon?: string;
            color?: string;
        };
        /** @description Полное состояние счёта в sync-операции (upsert). */
        AccountSyncData: {
            name: string;
            /** @enum {string} */
            currency: "USD" | "EUR" | "RUB";
            /** Format: int64 */
            openingBalance: number;
            /** Format: int64 */
            manualAdjustment: number;
        };
        /** @description Полное состояние категории в sync-операции (upsert). */
        CategorySyncData: {
            name: string;
            /** @enum {string} */
            type: "income" | "expense";
            icon: string;
            color: string;
        };
        /**
         * @description Полное состояние транзакции в sync-операции (upsert). Cashflow
         *     (income/expense) несёт `accountId`+`categoryId`, transfer —
         *     `fromAccountId`+`toAccountId`.
         */
        TransactionSyncData: {
            /** @enum {string} */
            type: "income" | "expense" | "transfer";
            /** Format: int64 */
            amount: number;
            description: string;
            /** Format: date-time */
            occurredAt: string;
            /** Format: uuid */
            accountId?: string | null;
            /** Format: uuid */
            categoryId?: string | null;
            /** Format: uuid */
            fromAccountId?: string | null;
            /** Format: uuid */
            toAccountId?: string | null;
        };
        /** @enum {string} */
        SyncEntity: "account" | "category" | "transaction";
        /**
         * @description Одна клиентская операция. `baseVersion` — серверная версия, на которой
         *     операция основана (0 = запись ещё не существует на сервере). Для
         *     upsert `data` содержит полное состояние записи; для delete `data`
         *     отсутствует.
         */
        SyncOperation: {
            /**
             * Format: uuid
             * @description Клиентский id операции; ключ постоянной идемпотентности.
             */
            opId: string;
            entity: components["schemas"]["SyncEntity"];
            /** @enum {string} */
            action: "upsert" | "delete";
            /**
             * Format: uuid
             * @description Id записи (клиентский UUID v4 для baseVersion = 0).
             */
            id: string;
            /** Format: int */
            baseVersion: number;
            /** @description Полное состояние записи; обязательно для upsert. */
            data?: components["schemas"]["AccountSyncData"] | components["schemas"]["CategorySyncData"] | components["schemas"]["TransactionSyncData"];
        };
        SyncPushRequest: {
            operations: components["schemas"]["SyncOperation"][];
        };
        /** @description Текущее состояние записи на сервере (в конфликте). */
        SyncServerState: {
            /** Format: int */
            version: number;
            /** @description true — запись tombstoned на сервере. */
            deleted: boolean;
            /** @description Присутствует для не удалённой записи. */
            data?: components["schemas"]["AccountSyncData"] | components["schemas"]["CategorySyncData"] | components["schemas"]["TransactionSyncData"];
        };
        /** @description Результат одной операции; HTTP ответ — всегда 200. */
        SyncPushResult: {
            /** Format: uuid */
            opId: string;
            /** @enum {string} */
            status: "applied" | "conflict" | "error";
            /**
             * Format: int
             * @description Новая серверная версия записи (для status = applied).
             */
            version?: number;
            /**
             * @description Machine-readable код (для conflict/error): `SYNC_VERSION_CONFLICT`,
             *     `SYNC_ALREADY_EXISTS`, `SYNC_DELETED_CONFLICT` либо коды
             *     бизнес-правил (`CATEGORY_IN_USE`, `INVALID_REFS`, ...).
             */
            code?: string;
            /** @description Human-readable сообщение (для conflict/error). */
            message?: string;
            serverState?: components["schemas"]["SyncServerState"];
        };
        SyncPushResponse: {
            results: components["schemas"]["SyncPushResult"][];
        };
        /** @description Одна запись change-log для pull. */
        SyncChange: {
            /**
             * Format: int64
             * @description Монотонный порядок изменения.
             */
            seq: number;
            entity: components["schemas"]["SyncEntity"];
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            action: "upsert" | "tombstone";
            /**
             * Format: int
             * @description Серверная версия записи после изменения.
             */
            version: number;
            /** @description Полное состояние записи; присутствует для upsert. */
            data?: components["schemas"]["AccountSyncData"] | components["schemas"]["CategorySyncData"] | components["schemas"]["TransactionSyncData"];
        };
        SyncPullResponse: {
            changes: components["schemas"]["SyncChange"][];
            /**
             * Format: int64
             * @description Курсор следующей страницы; null — клиент догнал сервер.
             */
            nextCursor: number | null;
        };
    };
    responses: {
        /** @description Не авторизован (нет валидной session cookie). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UNAUTHORIZED",
                 *       "message": "missing session cookie"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Внутренняя ошибка сервера. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "INTERNAL_ERROR",
                 *       "message": "internal server error"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Неверное тело запроса (validation failed). */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "VALIDATION_FAILED",
                 *       "message": "validation failed"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Транзакция не найдена (или чужая). */
        TransactionNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "TRANSACTION_NOT_FOUND",
                 *       "message": "transaction not found"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Конфликт в версии транзакции (optimistic concurrency). */
        TransactionVersionConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "TRANSACTION_VERSION_CONFLICT",
                 *       "message": "transaction version conflict"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Счёт не найден (или чужой). */
        AccountNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "ACCOUNT_NOT_FOUND",
                 *       "message": "account not found"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Категория не найдена (или чужая). */
        CategoryNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "CATEGORY_NOT_FOUND",
                 *       "message": "category not found"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Счёт имеет привязанные transactions, удаление невозможно. */
        AccountInUse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "ACCOUNT_IN_USE",
                 *       "message": "account has transactions and cannot be deleted"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Категория имеет привязанные transactions, удаление невозможно. */
        CategoryInUse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "CATEGORY_IN_USE",
                 *       "message": "category has transactions and cannot be deleted"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Категория с таким name уже есть у user. */
        CategoryAlreadyExists: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "CATEGORY_ALREADY_EXISTS",
                 *       "message": "category already exists"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Счет с таким id уже есть у user (клиентский id-дубликат). */
        AccountAlreadyExists: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "ACCOUNT_ALREADY_EXISTS",
                 *       "message": "account already exists"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Конфликт в версии счета (optimistic concurrency). */
        AccountVersionConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "ACCOUNT_VERSION_CONFLICT",
                 *       "message": "account version conflict"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        TransactionId: string;
        /**
         * @description Уникальный client-generated ключ (UUID recommended). Один ключ =
         *     один intent. Повтор того же запроса возвращает тот же ответ.
         */
        IdempotencyKey: string;
        AccountId: string;
        CategoryId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example user@example.com
                     */
                    email: string;
                    /**
                     * @description Plaintext (хешируется на сервере).
                     * @example strong-password
                     */
                    password: string;
                    /**
                     * @description Явно включить посев стартового набора категорий (24) для
                     *     этой регистрации. По умолчанию off — новый пользователь
                     *     начинает с пустым списком категорий.
                     * @default false
                     */
                    seedCategories?: boolean;
                };
            };
        };
        responses: {
            /** @description Пользователь создан, сессия установлена. */
            201: {
                headers: {
                    /** @description session_id cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Email уже занят. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "USER_ALREADY_EXISTS",
                     *       "message": "user already exists"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Успешный вход, сессия установлена. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Неверный email или пароль. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "INVALID_CREDENTIALS",
                     *       "message": "invalid credentials"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Слишком неудачных попыток входа с этого IP. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "TOO_MANY_REQUESTS",
                     *       "message": "too many login attempts, please try again later"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logoutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный выход (или cookie уже отсутствовал). */
            204: {
                headers: {
                    /** @description session_id cookie с Max-Age=-1 (browser удалит). */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Текущий пользователь по session cookie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список сессий. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteAllSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Все прочие сессии отозваны. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 123456 */
                    code: string;
                };
            };
        };
        responses: {
            /** @description Email подтверждён. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Код истёк / нет активного кода. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неверный код (attempts остаются). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "INVALID_VERIFICATION_CODE",
                     *       "message": "invalid verification code"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Email уже подтверждён. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "EMAIL_ALREADY_VERIFIED",
                     *       "message": "email already verified"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Brute-force lockout (per-IP). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "TOO_MANY_REQUESTS",
                     *       "message": "too many failed attempts, please try again later"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Новый код создан и "отправлен" (mailer-stub в dev). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email уже подтверждён. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "EMAIL_ALREADY_VERIFIED",
                     *       "message": "email already verified"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Throttle. */
            429: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "TOO_MANY_REQUESTS",
                     *       "message": "please wait before requesting a new code"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Всегда (anti-enumeration). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 256-bit hex token из reset-ссылки. */
                    token: string;
                    newPassword: string;
                };
            };
        };
        responses: {
            /** @description Пароль изменён, все сессии отозваны. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Невалидный/истёкший token или validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                type?: "income" | "expense" | "transfer";
                accountId?: string;
                categoryId?: string;
                /** @description ISO date (YYYY-MM-DD), lower bound inclusive. */
                fromDate?: string;
                /** @description ISO date (YYYY-MM-DD), upper bound inclusive. */
                toDate?: string;
                /** @description Page size (default 50, max 100). */
                limit?: number;
                /** @description Opaque курсор из nextCursor предыдущего ответа. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница транзакций + курсор следующей страницы. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        transactions: components["schemas"]["Transaction"][];
                        /** @description Opaque курсор; null если страниц больше нет. */
                        nextCursor: string | null;
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Уникальный client-generated ключ (UUID recommended). Один ключ =
                 *     один intent. Повтор того же запроса возвращает тот же ответ.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreateRequest"];
            };
        };
        responses: {
            /** @description Транзакция создана. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            /** @description Либо idempotency-конфликт, либо дубликат клиентского `id`. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Бизнес-правило нарушено — ссылки не найдены или type-mismatch. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Транзакция. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["TransactionNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалено. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["TransactionNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionUpdateRequest"];
            };
        };
        responses: {
            /** @description Обновлённая транзакция. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Либо validation failed, либо пустой body (`no fields to update`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["TransactionNotFound"];
            409: components["responses"]["TransactionVersionConflict"];
            /** @description То же, что у POST (бизнес-правило нарушено). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Счета текущего user с вычисленным balance. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreateRequest"];
            };
        };
        responses: {
            /** @description Счёт создан. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["AccountAlreadyExists"];
            500: components["responses"]["InternalError"];
        };
    };
    getAccountBalances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Балансы всех счетов и net worth. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountBalancesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Счёт. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["AccountNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалено. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["AccountNotFound"];
            409: components["responses"]["AccountInUse"];
            500: components["responses"]["InternalError"];
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdateRequest"];
            };
        };
        responses: {
            /** @description Обновлённый счёт. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["AccountNotFound"];
            409: components["responses"]["AccountVersionConflict"];
            500: components["responses"]["InternalError"];
        };
    };
    listCategories: {
        parameters: {
            query?: {
                type?: "income" | "expense";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Категории текущего user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreateRequest"];
            };
        };
        responses: {
            /** @description Категория создана. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["CategoryAlreadyExists"];
            500: components["responses"]["InternalError"];
        };
    };
    getCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Категория. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["CategoryNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалено. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["CategoryNotFound"];
            409: components["responses"]["CategoryInUse"];
            500: components["responses"]["InternalError"];
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdateRequest"];
            };
        };
        responses: {
            /** @description Обновлённая категория. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["CategoryNotFound"];
            /**
             * @description Либо имя уже занята (`CATEGORY_ALREADY_EXISTS`), либо конфликт
             *     версии (`CATEGORY_VERSION_CONFLICT`).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    syncPush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncPushRequest"];
            };
        };
        responses: {
            /** @description Per-item результаты в порядке операций запроса. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncPushResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    syncPull: {
        parameters: {
            query?: {
                /** @description Последний полученный seq (0 = с начала истории). */
                cursor?: number;
                /** @description Page size (default 100, max 500). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница изменений + nextCursor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncPullResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
}
