// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one

INSERT INTO accounts (user_id, name, currency, opening_balance, manual_adjustment)
VALUES ($1, $2, $3, $4, 0)
RETURNING
    id,
    user_id,
    name,
    currency,
    opening_balance,
    manual_adjustment,
    (opening_balance + manual_adjustment)::bigint AS balance,
    created_at,
    updated_at
`

type CreateAccountParams struct {
	UserID         uuid.UUID
	Name           string
	Currency       string
	OpeningBalance int64
}

type CreateAccountRow struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Name             string
	Currency         string
	OpeningBalance   int64
	ManualAdjustment int64
	Balance          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// accounts. Every query scopes by user_id (IDOR-safe: a cross-user access
// returns "not found", never the row). Balance is computed via the
// account_contributions view (opening + manual + sum(signed)).
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.Currency,
		arg.OpeningBalance,
	)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.OpeningBalance,
		&i.ManualAdjustment,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts WHERE id = $1 AND user_id = $2
`

type DeleteAccountParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccount = `-- name: GetAccount :one
SELECT
    a.id,
    a.user_id,
    a.name,
    a.currency,
    a.opening_balance,
    a.manual_adjustment,
    (a.opening_balance + a.manual_adjustment + COALESCE(SUM(c.signed), 0))::bigint AS balance,
    a.created_at,
    a.updated_at
FROM accounts a
LEFT JOIN account_contributions c ON c.account_id = a.id
WHERE a.id = $1 AND a.user_id = $2
GROUP BY a.id, a.user_id, a.name, a.currency, a.opening_balance, a.manual_adjustment, a.created_at, a.updated_at
`

type GetAccountParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetAccountRow struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Name             string
	Currency         string
	OpeningBalance   int64
	ManualAdjustment int64
	Balance          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.ID, arg.UserID)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.OpeningBalance,
		&i.ManualAdjustment,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountBalances = `-- name: GetAccountBalances :many
SELECT
    a.id,
    a.user_id,
    a.name,
    a.currency,
    (a.opening_balance + a.manual_adjustment + COALESCE(SUM(c.signed), 0))::bigint AS balance
FROM accounts a
LEFT JOIN account_contributions c ON c.account_id = a.id
WHERE a.user_id = $1
GROUP BY a.id, a.user_id, a.name, a.currency, a.opening_balance, a.manual_adjustment
ORDER BY a.created_at, a.id
`

type GetAccountBalancesRow struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Name     string
	Currency string
	Balance  int64
}

func (q *Queries) GetAccountBalances(ctx context.Context, userID uuid.UUID) ([]GetAccountBalancesRow, error) {
	rows, err := q.db.Query(ctx, getAccountBalances, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountBalancesRow
	for rows.Next() {
		var i GetAccountBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Currency,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccounts = `-- name: GetAccounts :many
SELECT
    a.id,
    a.user_id,
    a.name,
    a.currency,
    a.opening_balance,
    a.manual_adjustment,
    (a.opening_balance + a.manual_adjustment + COALESCE(SUM(c.signed), 0))::bigint AS balance,
    a.created_at,
    a.updated_at
FROM accounts a
LEFT JOIN account_contributions c ON c.account_id = a.id
WHERE a.user_id = $1
GROUP BY a.id, a.user_id, a.name, a.currency, a.opening_balance, a.manual_adjustment, a.created_at, a.updated_at
ORDER BY a.created_at, a.id
`

type GetAccountsRow struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Name             string
	Currency         string
	OpeningBalance   int64
	ManualAdjustment int64
	Balance          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) GetAccounts(ctx context.Context, userID uuid.UUID) ([]GetAccountsRow, error) {
	rows, err := q.db.Query(ctx, getAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountsRow
	for rows.Next() {
		var i GetAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Currency,
			&i.OpeningBalance,
			&i.ManualAdjustment,
			&i.Balance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET
    name              = COALESCE($1, name),
    manual_adjustment = COALESCE($2, manual_adjustment),
    updated_at        = now()
WHERE id = $3 AND user_id = $4
RETURNING
    id,
    user_id,
    name,
    currency,
    opening_balance,
    manual_adjustment,
    (opening_balance + manual_adjustment + COALESCE(
        (SELECT SUM(c.signed) FROM account_contributions c WHERE c.account_id = accounts.id), 0
    ))::bigint AS balance,
    created_at,
    updated_at
`

type UpdateAccountParams struct {
	Name             *string
	ManualAdjustment *int64
	ID               uuid.UUID
	UserID           uuid.UUID
}

type UpdateAccountRow struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Name             string
	Currency         string
	OpeningBalance   int64
	ManualAdjustment int64
	Balance          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// COALESCE keeps a column unchanged when its narg is NULL (PATCH semantics).
func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (UpdateAccountRow, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.Name,
		arg.ManualAdjustment,
		arg.ID,
		arg.UserID,
	)
	var i UpdateAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.OpeningBalance,
		&i.ManualAdjustment,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
