// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const latestPasswordResetTokenAgeSeconds = `-- name: LatestPasswordResetTokenAgeSeconds :one
SELECT EXTRACT(EPOCH FROM (now() - created_at))::int AS age_seconds
FROM password_reset_tokens
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) LatestPasswordResetTokenAgeSeconds(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, latestPasswordResetTokenAgeSeconds, userID)
	var age_seconds int32
	err := row.Scan(&age_seconds)
	return age_seconds, err
}

const latestVerificationCodeAgeSeconds = `-- name: LatestVerificationCodeAgeSeconds :one

SELECT EXTRACT(EPOCH FROM (now() - created_at))::int AS age_seconds
FROM email_verification_codes
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

// email verification + password reset throttling helpers.
// Each returns the age in seconds of the most recently issued code/token for a
// user, or no rows when none exists (the repository maps that to "no active").
func (q *Queries) LatestVerificationCodeAgeSeconds(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, latestVerificationCodeAgeSeconds, userID)
	var age_seconds int32
	err := row.Scan(&age_seconds)
	return age_seconds, err
}
