// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one

INSERT INTO categories (user_id, name, type, icon, color)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, type, icon, color, created_at, updated_at
`

type CreateCategoryParams struct {
	UserID uuid.UUID
	Name   string
	Type   string
	Icon   string
	Color  string
}

// categories (per-user, unique name within user). Scoped by user_id everywhere.
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Icon,
		arg.Color,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories WHERE id = $1 AND user_id = $2
`

type DeleteCategoryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategories = `-- name: GetCategories :many
SELECT id, user_id, name, type, icon, color, created_at, updated_at
FROM categories
WHERE
    user_id = $1
    AND ($2::text IS NULL OR type = $2)
ORDER BY created_at, id
`

type GetCategoriesParams struct {
	UserID uuid.UUID
	Type   *string
}

func (q *Queries) GetCategories(ctx context.Context, arg GetCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategories, arg.UserID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Icon,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, user_id, name, type, icon, color, created_at, updated_at
FROM categories
WHERE id = $1 AND user_id = $2
`

type GetCategoryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name       = COALESCE($1, name),
    type       = COALESCE($2, type),
    icon       = COALESCE($3, icon),
    color      = COALESCE($4, color),
    updated_at = now()
WHERE id = $5 AND user_id = $6
RETURNING id, user_id, name, type, icon, color, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name   *string
	Type   *string
	Icon   *string
	Color  *string
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Type,
		arg.Icon,
		arg.Color,
		arg.ID,
		arg.UserID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
