// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const categoryNameTaken = `-- name: CategoryNameTaken :one
SELECT EXISTS(
    SELECT 1
    FROM categories
    WHERE household_id = $1 AND name = $2 AND deleted_at IS NULL AND id <> $3
) AS taken
`

type CategoryNameTakenParams struct {
	HouseholdID uuid.UUID
	Name        string
	ExceptID    uuid.UUID
}

// Live-name uniqueness pre-check (race-free under the per-household
// change-log advisory lock); used by the sync path where a constraint
// violation would abort the shared batch transaction.
func (q *Queries) CategoryNameTaken(ctx context.Context, arg CategoryNameTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, categoryNameTaken, arg.HouseholdID, arg.Name, arg.ExceptID)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const createCategory = `-- name: CreateCategory :one

INSERT INTO categories (id, household_id, user_id, name, type, icon, color, archived_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, type, icon, color, archived_at, created_at, updated_at, version
`

type CreateCategoryParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	UserID      uuid.UUID
	Name        string
	Type        string
	Icon        string
	Color       string
	ArchivedAt  *time.Time
}

type CreateCategoryRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Type       string
	Icon       string
	Color      string
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Version    int32
}

// categories (household-scoped, unique name among LIVE rows only - the
// partial unique index ignores tombstones so a deleted name can be recreated).
// Scoped by household_id everywhere; user_id stays on rows as authorship;
// deletes are soft (deleted_at tombstone).
// id is the optional client-generated id (offline-first clients);
// archived_at rides along so an offline-archived unborn record syncs as-is.
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.HouseholdID,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Icon,
		arg.Color,
		arg.ArchivedAt,
	)
	var i CreateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCategories = `-- name: GetCategories :many
SELECT id, user_id, name, type, icon, color, archived_at, created_at, updated_at, version
FROM categories
WHERE
    household_id = $1
    AND deleted_at IS NULL
    AND ($2::boolean OR archived_at IS NULL)
    AND ($3::text IS NULL OR type = $3)
ORDER BY created_at, id
`

type GetCategoriesParams struct {
	HouseholdID     uuid.UUID
	IncludeArchived bool
	Type            *string
}

type GetCategoriesRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Type       string
	Icon       string
	Color      string
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Version    int32
}

// Active-only by default; include_archived flips the archived_at filter for
// management listings.
func (q *Queries) GetCategories(ctx context.Context, arg GetCategoriesParams) ([]GetCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getCategories, arg.HouseholdID, arg.IncludeArchived, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoriesRow
	for rows.Next() {
		var i GetCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Icon,
			&i.Color,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, user_id, name, type, icon, color, archived_at, created_at, updated_at, version
FROM categories
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type GetCategoryParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

type GetCategoryRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Type       string
	Icon       string
	Color      string
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Version    int32
}

// Live read including archived rows (archived categories stay visible to
// their management UI and to reference validation).
func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (GetCategoryRow, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.HouseholdID)
	var i GetCategoryRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCategoryAny = `-- name: GetCategoryAny :one
SELECT id, user_id, name, type, icon, color, archived_at, created_at, updated_at, version, deleted_at
FROM categories
WHERE id = $1 AND household_id = $2
`

type GetCategoryAnyParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

type GetCategoryAnyRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Type       string
	Icon       string
	Color      string
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Version    int32
	DeletedAt  *time.Time
}

// Includes tombstoned rows (sync push + conflict classification).
func (q *Queries) GetCategoryAny(ctx context.Context, arg GetCategoryAnyParams) (GetCategoryAnyRow, error) {
	row := q.db.QueryRow(ctx, getCategoryAny, arg.ID, arg.HouseholdID)
	var i GetCategoryAnyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.DeletedAt,
	)
	return i, err
}

const hasLiveTransactionsForCategory = `-- name: HasLiveTransactionsForCategory :one
SELECT EXISTS(
    SELECT 1
    FROM transactions
    WHERE household_id = $1 AND deleted_at IS NULL AND category_id = $2
) AS in_use
`

type HasLiveTransactionsForCategoryParams struct {
	HouseholdID uuid.UUID
	CategoryID  *uuid.UUID
}

func (q *Queries) HasLiveTransactionsForCategory(ctx context.Context, arg HasLiveTransactionsForCategoryParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasLiveTransactionsForCategory, arg.HouseholdID, arg.CategoryID)
	var in_use bool
	err := row.Scan(&in_use)
	return in_use, err
}

const softDeleteCategory = `-- name: SoftDeleteCategory :one
UPDATE categories
SET deleted_at = now(), version = version + 1, updated_at = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
RETURNING version
`

type SoftDeleteCategoryParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) (int32, error) {
	row := q.db.QueryRow(ctx, softDeleteCategory, arg.ID, arg.HouseholdID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const softDeleteTransactionsForCategory = `-- name: SoftDeleteTransactionsForCategory :many
UPDATE transactions
SET deleted_at = now(), version = version + 1, updated_at = now()
WHERE household_id = $1 AND category_id = $2 AND deleted_at IS NULL
RETURNING id, version
`

type SoftDeleteTransactionsForCategoryParams struct {
	HouseholdID uuid.UUID
	CategoryID  *uuid.UUID
}

type SoftDeleteTransactionsForCategoryRow struct {
	ID      uuid.UUID
	Version int32
}

// Cascade half of a category delete: tombstone every live transaction of
// the household referencing the category (balances are derived from live
// transactions, so they recompute implicitly). Returns id+version per row
// for the per-record change_log appends.
func (q *Queries) SoftDeleteTransactionsForCategory(ctx context.Context, arg SoftDeleteTransactionsForCategoryParams) ([]SoftDeleteTransactionsForCategoryRow, error) {
	rows, err := q.db.Query(ctx, softDeleteTransactionsForCategory, arg.HouseholdID, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SoftDeleteTransactionsForCategoryRow
	for rows.Next() {
		var i SoftDeleteTransactionsForCategoryRow
		if err := rows.Scan(&i.ID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncCategoriesByIDs = `-- name: SyncCategoriesByIDs :many
SELECT id, user_id, name, type, icon, color, archived_at, version, deleted_at
FROM categories
WHERE household_id = $1 AND id = ANY($2::uuid[])
`

type SyncCategoriesByIDsParams struct {
	HouseholdID uuid.UUID
	Ids         []uuid.UUID
}

type SyncCategoriesByIDsRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Type       string
	Icon       string
	Color      string
	ArchivedAt *time.Time
	Version    int32
	DeletedAt  *time.Time
}

func (q *Queries) SyncCategoriesByIDs(ctx context.Context, arg SyncCategoriesByIDsParams) ([]SyncCategoriesByIDsRow, error) {
	rows, err := q.db.Query(ctx, syncCategoriesByIDs, arg.HouseholdID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncCategoriesByIDsRow
	for rows.Next() {
		var i SyncCategoriesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Icon,
			&i.Color,
			&i.ArchivedAt,
			&i.Version,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncReplaceCategory = `-- name: SyncReplaceCategory :one
UPDATE categories
SET
    name         = $1,
    type         = $2,
    icon         = $3,
    color        = $4,
    archived_at  = $5,
    version      = version + 1,
    updated_at   = now()
WHERE id = $6 AND household_id = $7 AND deleted_at IS NULL AND version = $8
RETURNING id, user_id, name, type, icon, color, archived_at, created_at, updated_at, version
`

type SyncReplaceCategoryParams struct {
	Name        string
	Type        string
	Icon        string
	Color       string
	ArchivedAt  *time.Time
	ID          uuid.UUID
	HouseholdID uuid.UUID
	BaseVersion int32
}

type SyncReplaceCategoryRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Type       string
	Icon       string
	Color      string
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Version    int32
}

// Full-state CAS upsert from a sync push.
func (q *Queries) SyncReplaceCategory(ctx context.Context, arg SyncReplaceCategoryParams) (SyncReplaceCategoryRow, error) {
	row := q.db.QueryRow(ctx, syncReplaceCategory,
		arg.Name,
		arg.Type,
		arg.Icon,
		arg.Color,
		arg.ArchivedAt,
		arg.ID,
		arg.HouseholdID,
		arg.BaseVersion,
	)
	var i SyncReplaceCategoryRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name         = COALESCE($1, name),
    type         = COALESCE($2, type),
    icon         = COALESCE($3, icon),
    color        = COALESCE($4, color),
    archived_at  = CASE $5::text
                      WHEN 'archive' THEN now()
                      WHEN 'clear'   THEN NULL
                      ELSE archived_at
                  END,
    version      = version + 1,
    updated_at   = now()
WHERE id = $6 AND household_id = $7 AND deleted_at IS NULL AND version = $8
RETURNING id, user_id, name, type, icon, color, archived_at, created_at, updated_at, version
`

type UpdateCategoryParams struct {
	Name           *string
	Type           *string
	Icon           *string
	Color          *string
	ArchivedAction string
	ID             uuid.UUID
	HouseholdID    uuid.UUID
	Version        int32
}

type UpdateCategoryRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Type       string
	Icon       string
	Color      string
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Version    int32
}

// Optimistic concurrency: the WHERE clause includes version = @version (and
// liveness) so a concurrent update yields zero rows. PATCH fields use
// COALESCE for nil = keep. archived_action is a tri-state text sentinel:
// 'keep' leaves archived_at, 'archive' stamps now() server-side, 'clear'
// unarchives (the PATCH contract carries a boolean, never a timestamp).
func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (UpdateCategoryRow, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Type,
		arg.Icon,
		arg.Color,
		arg.ArchivedAction,
		arg.ID,
		arg.HouseholdID,
		arg.Version,
	)
	var i UpdateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
