// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: debtors.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDebtor = `-- name: CreateDebtor :one

INSERT INTO debtors (id, user_id, name, note)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, note, created_at, updated_at, version
`

type CreateDebtorParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Name   string
	Note   string
}

type CreateDebtorRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Note      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Version   int32
}

// debtors (per-user, unique name among LIVE rows only - the partial unique
// index ignores tombstones so a deleted name can be recreated). Scoped by
// user_id everywhere; deletes are soft (deleted_at tombstone).
// id is the optional client-generated id (offline-first clients).
func (q *Queries) CreateDebtor(ctx context.Context, arg CreateDebtorParams) (CreateDebtorRow, error) {
	row := q.db.QueryRow(ctx, createDebtor,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Note,
	)
	var i CreateDebtorRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const debtorNameTaken = `-- name: DebtorNameTaken :one
SELECT EXISTS(
    SELECT 1
    FROM debtors
    WHERE user_id = $1 AND name = $2 AND deleted_at IS NULL AND id <> $3
) AS taken
`

type DebtorNameTakenParams struct {
	UserID   uuid.UUID
	Name     string
	ExceptID uuid.UUID
}

// Live-name uniqueness pre-check (race-free under the per-user change-log
// advisory lock); used by the sync path where a constraint violation would
// abort the shared batch transaction.
func (q *Queries) DebtorNameTaken(ctx context.Context, arg DebtorNameTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, debtorNameTaken, arg.UserID, arg.Name, arg.ExceptID)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const getDebtor = `-- name: GetDebtor :one
SELECT id, user_id, name, note, created_at, updated_at, version
FROM debtors
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetDebtorParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetDebtorRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Note      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Version   int32
}

func (q *Queries) GetDebtor(ctx context.Context, arg GetDebtorParams) (GetDebtorRow, error) {
	row := q.db.QueryRow(ctx, getDebtor, arg.ID, arg.UserID)
	var i GetDebtorRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getDebtorAny = `-- name: GetDebtorAny :one
SELECT id, user_id, name, note, created_at, updated_at, version, deleted_at
FROM debtors
WHERE id = $1 AND user_id = $2
`

type GetDebtorAnyParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Includes tombstoned rows (sync push + conflict classification).
func (q *Queries) GetDebtorAny(ctx context.Context, arg GetDebtorAnyParams) (Debtor, error) {
	row := q.db.QueryRow(ctx, getDebtorAny, arg.ID, arg.UserID)
	var i Debtor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.DeletedAt,
	)
	return i, err
}

const getDebtors = `-- name: GetDebtors :many
SELECT id, user_id, name, note, created_at, updated_at, version
FROM debtors
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at, id
`

type GetDebtorsRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Note      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Version   int32
}

func (q *Queries) GetDebtors(ctx context.Context, userID uuid.UUID) ([]GetDebtorsRow, error) {
	rows, err := q.db.Query(ctx, getDebtors, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDebtorsRow
	for rows.Next() {
		var i GetDebtorsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasLiveDebtOperationsForDebtor = `-- name: HasLiveDebtOperationsForDebtor :one
SELECT EXISTS(
    SELECT 1
    FROM debt_operations
    WHERE user_id = $1 AND deleted_at IS NULL AND debtor_id = $2
) AS in_use
`

type HasLiveDebtOperationsForDebtorParams struct {
	UserID   uuid.UUID
	DebtorID uuid.UUID
}

// In-use guard counts LIVE operations only: tombstoned operations never
// block debtor deletion.
func (q *Queries) HasLiveDebtOperationsForDebtor(ctx context.Context, arg HasLiveDebtOperationsForDebtorParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasLiveDebtOperationsForDebtor, arg.UserID, arg.DebtorID)
	var in_use bool
	err := row.Scan(&in_use)
	return in_use, err
}

const softDeleteDebtor = `-- name: SoftDeleteDebtor :one
UPDATE debtors
SET deleted_at = now(), version = version + 1, updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING version
`

type SoftDeleteDebtorParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) SoftDeleteDebtor(ctx context.Context, arg SoftDeleteDebtorParams) (int32, error) {
	row := q.db.QueryRow(ctx, softDeleteDebtor, arg.ID, arg.UserID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const syncDebtorsByIDs = `-- name: SyncDebtorsByIDs :many
SELECT id, user_id, name, note, version, deleted_at
FROM debtors
WHERE user_id = $1 AND id = ANY($2::uuid[])
`

type SyncDebtorsByIDsParams struct {
	UserID uuid.UUID
	Ids    []uuid.UUID
}

type SyncDebtorsByIDsRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Note      string
	Version   int32
	DeletedAt *time.Time
}

func (q *Queries) SyncDebtorsByIDs(ctx context.Context, arg SyncDebtorsByIDsParams) ([]SyncDebtorsByIDsRow, error) {
	rows, err := q.db.Query(ctx, syncDebtorsByIDs, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncDebtorsByIDsRow
	for rows.Next() {
		var i SyncDebtorsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Note,
			&i.Version,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncReplaceDebtor = `-- name: SyncReplaceDebtor :one
UPDATE debtors
SET
    name       = $1,
    note       = $2,
    version    = version + 1,
    updated_at = now()
WHERE id = $3 AND user_id = $4 AND deleted_at IS NULL AND version = $5
RETURNING id, user_id, name, note, created_at, updated_at, version
`

type SyncReplaceDebtorParams struct {
	Name        string
	Note        string
	ID          uuid.UUID
	UserID      uuid.UUID
	BaseVersion int32
}

type SyncReplaceDebtorRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Note      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Version   int32
}

// Full-state CAS upsert from a sync push.
func (q *Queries) SyncReplaceDebtor(ctx context.Context, arg SyncReplaceDebtorParams) (SyncReplaceDebtorRow, error) {
	row := q.db.QueryRow(ctx, syncReplaceDebtor,
		arg.Name,
		arg.Note,
		arg.ID,
		arg.UserID,
		arg.BaseVersion,
	)
	var i SyncReplaceDebtorRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateDebtor = `-- name: UpdateDebtor :one
UPDATE debtors
SET
    name       = COALESCE($1, name),
    note       = COALESCE($2, note),
    version    = version + 1,
    updated_at = now()
WHERE id = $3 AND user_id = $4 AND deleted_at IS NULL AND version = $5
RETURNING id, user_id, name, note, created_at, updated_at, version
`

type UpdateDebtorParams struct {
	Name    *string
	Note    *string
	ID      uuid.UUID
	UserID  uuid.UUID
	Version int32
}

type UpdateDebtorRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Note      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Version   int32
}

// Optimistic concurrency: the WHERE clause includes version = @version (and
// liveness) so a concurrent update yields zero rows. PATCH fields use
// COALESCE for nil = keep; a non-nil empty note clears it.
func (q *Queries) UpdateDebtor(ctx context.Context, arg UpdateDebtorParams) (UpdateDebtorRow, error) {
	row := q.db.QueryRow(ctx, updateDebtor,
		arg.Name,
		arg.Note,
		arg.ID,
		arg.UserID,
		arg.Version,
	)
	var i UpdateDebtorRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
