// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one

INSERT INTO idempotency_keys (idempotency_key, user_id, request_hash, status, expires_at)
VALUES ($1, $2, $3, 'pending', $4)
RETURNING
    id, idempotency_key, user_id, request_hash, status,
    response_status, response_headers, response_body,
    created_at, updated_at, expires_at
`

type CreateIdempotencyKeyParams struct {
	IdempotencyKey string
	UserID         uuid.UUID
	RequestHash    string
	ExpiresAt      time.Time
}

// idempotency keys (POST /api/transactions idempotency cache).
// user_id is a uuid; the idempotency_key value is a client string.
func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.IdempotencyKey,
		arg.UserID,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.UserID,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :execrows
DELETE FROM idempotency_keys WHERE id = $1 AND user_id = $2
`

type DeleteIdempotencyKeyParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteIdempotencyKey(ctx context.Context, arg DeleteIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdempotencyKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyByUserAndKey = `-- name: GetIdempotencyByUserAndKey :one
SELECT
    id, idempotency_key, user_id, request_hash, status,
    response_status, response_headers, response_body,
    created_at, updated_at, expires_at
FROM idempotency_keys
WHERE user_id = $1 AND idempotency_key = $2
`

type GetIdempotencyByUserAndKeyParams struct {
	UserID         uuid.UUID
	IdempotencyKey string
}

func (q *Queries) GetIdempotencyByUserAndKey(ctx context.Context, arg GetIdempotencyByUserAndKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyByUserAndKey, arg.UserID, arg.IdempotencyKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.UserID,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateIdempotencyKey = `-- name: UpdateIdempotencyKey :one
UPDATE idempotency_keys
SET
    status           = COALESCE($1, status),
    response_status  = $2,
    response_headers = COALESCE($3, response_headers),
    response_body    = COALESCE($4, response_body),
    updated_at       = now()
WHERE id = $5 AND user_id = $6
RETURNING
    id, idempotency_key, user_id, request_hash, status,
    response_status, response_headers, response_body,
    created_at, updated_at, expires_at
`

type UpdateIdempotencyKeyParams struct {
	Status          *string
	ResponseStatus  *int32
	ResponseHeaders *string
	ResponseBody    []byte
	ID              uuid.UUID
	UserID          uuid.UUID
}

func (q *Queries) UpdateIdempotencyKey(ctx context.Context, arg UpdateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, updateIdempotencyKey,
		arg.Status,
		arg.ResponseStatus,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.ID,
		arg.UserID,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.UserID,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
