// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Name             string
	OpeningBalance   int64
	ManualAdjustment int64
	Currency         string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        *time.Time
	Version          int32
	HouseholdID      uuid.UUID
}

type AccountContribution struct {
	AccountID *uuid.UUID
	Signed    interface{}
}

type AppliedOperation struct {
	OpID        uuid.UUID
	UserID      uuid.UUID
	Entity      string
	EntityID    uuid.UUID
	Result      []byte
	AppliedAt   time.Time
	HouseholdID uuid.UUID
}

type Category struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Type        string
	Icon        string
	Color       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
	Version     int32
	HouseholdID uuid.UUID
}

type ChangeLog struct {
	Seq         int64
	UserID      uuid.UUID
	Entity      string
	EntityID    uuid.UUID
	Action      string
	Version     int32
	CreatedAt   time.Time
	HouseholdID uuid.UUID
}

type DebtOperation struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	DebtorID    uuid.UUID
	Direction   string
	Kind        string
	Amount      int64
	Note        string
	OccurredAt  time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Version     int32
	DeletedAt   *time.Time
	HouseholdID uuid.UUID
}

type Debtor struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Note        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Version     int32
	DeletedAt   *time.Time
	HouseholdID uuid.UUID
}

type EmailVerificationCode struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Code      string
	Attempts  int32
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Household struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

type HouseholdMember struct {
	HouseholdID uuid.UUID
	UserID      uuid.UUID
	Role        string
	JoinedAt    time.Time
}

type IdempotencyKey struct {
	ID              uuid.UUID
	IdempotencyKey  string
	UserID          uuid.UUID
	RequestHash     string
	Status          string
	ResponseStatus  *int32
	ResponseHeaders *string
	ResponseBody    []byte
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ExpiresAt       time.Time
}

type PasswordResetToken struct {
	TokenHash string
	UserID    uuid.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
}

type PlannedPayment struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Type        string
	Amount      int64
	Name        string
	AccountID   uuid.UUID
	CategoryID  uuid.UUID
	NextDue     time.Time
	AnchorDate  time.Time
	Regularity  string
	ConfirmMode string
	Reminder    string
	Note        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Version     int32
	DeletedAt   *time.Time
	HouseholdID uuid.UUID
}

type Session struct {
	ID        string
	UserID    uuid.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Transaction struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Type          string
	Amount        int64
	Description   string
	OccurredAt    time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Version       int32
	AccountID     *uuid.UUID
	CategoryID    *uuid.UUID
	FromAccountID *uuid.UUID
	ToAccountID   *uuid.UUID
	DeletedAt     *time.Time
	HouseholdID   uuid.UUID
}

type User struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	EmailVerifiedAt *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DisplayName     *string
}
