// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planned_payments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const advancePlannedPayment = `-- name: AdvancePlannedPayment :one
UPDATE planned_payments
SET next_due = $1, version = version + 1, updated_at = now()
WHERE id = $2 AND user_id = $3 AND deleted_at IS NULL
RETURNING id, user_id, type, amount, name, account_id, category_id,
          next_due, anchor_date, regularity, confirm_mode, reminder, note,
          created_at, updated_at, version
`

type AdvancePlannedPaymentParams struct {
	NextDue time.Time
	ID      uuid.UUID
	UserID  uuid.UUID
}

type AdvancePlannedPaymentRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Type        string
	Amount      int64
	Name        string
	AccountID   uuid.UUID
	CategoryID  uuid.UUID
	NextDue     time.Time
	AnchorDate  time.Time
	Regularity  string
	ConfirmMode string
	Reminder    string
	Note        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Version     int32
}

// Server-side occurrence advancement (auto-confirm job): bumps next_due to
// the already-computed next occurrence. Optimistic-concurrency-free on
// purpose - the job runs under the per-user advisory lock and owns the row
// for the duration of the transaction that creates the payment.
func (q *Queries) AdvancePlannedPayment(ctx context.Context, arg AdvancePlannedPaymentParams) (AdvancePlannedPaymentRow, error) {
	row := q.db.QueryRow(ctx, advancePlannedPayment, arg.NextDue, arg.ID, arg.UserID)
	var i AdvancePlannedPaymentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Name,
		&i.AccountID,
		&i.CategoryID,
		&i.NextDue,
		&i.AnchorDate,
		&i.Regularity,
		&i.ConfirmMode,
		&i.Reminder,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createPlannedPayment = `-- name: CreatePlannedPayment :one

INSERT INTO planned_payments (
    id, user_id, type, amount, name, account_id, category_id,
    next_due, anchor_date, regularity, confirm_mode, reminder, note
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8, $9, $10, $11, $12)
RETURNING id, user_id, type, amount, name, account_id, category_id,
          next_due, anchor_date, regularity, confirm_mode, reminder, note,
          created_at, updated_at, version
`

type CreatePlannedPaymentParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Type        string
	Amount      int64
	Name        string
	AccountID   uuid.UUID
	CategoryID  uuid.UUID
	NextDue     time.Time
	Regularity  string
	ConfirmMode string
	Reminder    string
	Note        string
}

type CreatePlannedPaymentRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Type        string
	Amount      int64
	Name        string
	AccountID   uuid.UUID
	CategoryID  uuid.UUID
	NextDue     time.Time
	AnchorDate  time.Time
	Regularity  string
	ConfirmMode string
	Reminder    string
	Note        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Version     int32
}

// planned_payments (per-user recurring expense/income rules). Name is NOT
// unique (two live "Netflix" plans are legal). Scoped by user_id everywhere;
// deletes are soft (deleted_at tombstone). next_due/anchor_date are
// day-granularity dates; advancement touches next_due only, so the anchor
// survives clamped months.
// id is the optional client-generated id (offline-first clients). next_due
// doubles as the initial anchor.
func (q *Queries) CreatePlannedPayment(ctx context.Context, arg CreatePlannedPaymentParams) (CreatePlannedPaymentRow, error) {
	row := q.db.QueryRow(ctx, createPlannedPayment,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Amount,
		arg.Name,
		arg.AccountID,
		arg.CategoryID,
		arg.NextDue,
		arg.Regularity,
		arg.ConfirmMode,
		arg.Reminder,
		arg.Note,
	)
	var i CreatePlannedPaymentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Name,
		&i.AccountID,
		&i.CategoryID,
		&i.NextDue,
		&i.AnchorDate,
		&i.Regularity,
		&i.ConfirmMode,
		&i.Reminder,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const dueAutoPlannedPayments = `-- name: DueAutoPlannedPayments :many
SELECT id, user_id, type, amount, name, account_id, category_id,
       next_due, anchor_date, regularity, confirm_mode, reminder, note,
       created_at, updated_at, version
FROM planned_payments
WHERE user_id = $1
  AND deleted_at IS NULL
  AND confirm_mode = 'auto'
  AND next_due <= $2
ORDER BY next_due ASC, id ASC
`

type DueAutoPlannedPaymentsParams struct {
	UserID uuid.UUID
	Today  time.Time
}

type DueAutoPlannedPaymentsRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Type        string
	Amount      int64
	Name        string
	AccountID   uuid.UUID
	CategoryID  uuid.UUID
	NextDue     time.Time
	AnchorDate  time.Time
	Regularity  string
	ConfirmMode string
	Reminder    string
	Note        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Version     int32
}

// The auto-confirm job's due scan: live auto plans whose next occurrence
// date has arrived (UTC today inclusive).
func (q *Queries) DueAutoPlannedPayments(ctx context.Context, arg DueAutoPlannedPaymentsParams) ([]DueAutoPlannedPaymentsRow, error) {
	rows, err := q.db.Query(ctx, dueAutoPlannedPayments, arg.UserID, arg.Today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DueAutoPlannedPaymentsRow
	for rows.Next() {
		var i DueAutoPlannedPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Amount,
			&i.Name,
			&i.AccountID,
			&i.CategoryID,
			&i.NextDue,
			&i.AnchorDate,
			&i.Regularity,
			&i.ConfirmMode,
			&i.Reminder,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlannedPayment = `-- name: GetPlannedPayment :one
SELECT id, user_id, type, amount, name, account_id, category_id,
       next_due, anchor_date, regularity, confirm_mode, reminder, note,
       created_at, updated_at, version
FROM planned_payments
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetPlannedPaymentParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetPlannedPaymentRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Type        string
	Amount      int64
	Name        string
	AccountID   uuid.UUID
	CategoryID  uuid.UUID
	NextDue     time.Time
	AnchorDate  time.Time
	Regularity  string
	ConfirmMode string
	Reminder    string
	Note        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Version     int32
}

func (q *Queries) GetPlannedPayment(ctx context.Context, arg GetPlannedPaymentParams) (GetPlannedPaymentRow, error) {
	row := q.db.QueryRow(ctx, getPlannedPayment, arg.ID, arg.UserID)
	var i GetPlannedPaymentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Name,
		&i.AccountID,
		&i.CategoryID,
		&i.NextDue,
		&i.AnchorDate,
		&i.Regularity,
		&i.ConfirmMode,
		&i.Reminder,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getPlannedPaymentAny = `-- name: GetPlannedPaymentAny :one
SELECT id, user_id, type, amount, name, account_id, category_id,
       next_due, anchor_date, regularity, confirm_mode, reminder, note,
       created_at, updated_at, version, deleted_at
FROM planned_payments
WHERE id = $1 AND user_id = $2
`

type GetPlannedPaymentAnyParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Includes tombstoned rows (sync push + conflict classification).
func (q *Queries) GetPlannedPaymentAny(ctx context.Context, arg GetPlannedPaymentAnyParams) (PlannedPayment, error) {
	row := q.db.QueryRow(ctx, getPlannedPaymentAny, arg.ID, arg.UserID)
	var i PlannedPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Name,
		&i.AccountID,
		&i.CategoryID,
		&i.NextDue,
		&i.AnchorDate,
		&i.Regularity,
		&i.ConfirmMode,
		&i.Reminder,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.DeletedAt,
	)
	return i, err
}

const getPlannedPayments = `-- name: GetPlannedPayments :many
SELECT id, user_id, type, amount, name, account_id, category_id,
       next_due, anchor_date, regularity, confirm_mode, reminder, note,
       created_at, updated_at, version
FROM planned_payments
WHERE
    user_id = $1
    AND deleted_at IS NULL
    AND ($2::text IS NULL OR type = $2)
ORDER BY next_due ASC, id ASC
`

type GetPlannedPaymentsParams struct {
	UserID uuid.UUID
	Type   *string
}

type GetPlannedPaymentsRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Type        string
	Amount      int64
	Name        string
	AccountID   uuid.UUID
	CategoryID  uuid.UUID
	NextDue     time.Time
	AnchorDate  time.Time
	Regularity  string
	ConfirmMode string
	Reminder    string
	Note        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Version     int32
}

func (q *Queries) GetPlannedPayments(ctx context.Context, arg GetPlannedPaymentsParams) ([]GetPlannedPaymentsRow, error) {
	rows, err := q.db.Query(ctx, getPlannedPayments, arg.UserID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlannedPaymentsRow
	for rows.Next() {
		var i GetPlannedPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Amount,
			&i.Name,
			&i.AccountID,
			&i.CategoryID,
			&i.NextDue,
			&i.AnchorDate,
			&i.Regularity,
			&i.ConfirmMode,
			&i.Reminder,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasLivePlannedPaymentsForAccount = `-- name: HasLivePlannedPaymentsForAccount :one
SELECT EXISTS(
    SELECT 1
    FROM planned_payments
    WHERE user_id = $1 AND deleted_at IS NULL AND account_id = $2
) AS in_use
`

type HasLivePlannedPaymentsForAccountParams struct {
	UserID    uuid.UUID
	AccountID uuid.UUID
}

// In-use guard counts LIVE plans only: tombstoned plans never block account
// deletion.
func (q *Queries) HasLivePlannedPaymentsForAccount(ctx context.Context, arg HasLivePlannedPaymentsForAccountParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasLivePlannedPaymentsForAccount, arg.UserID, arg.AccountID)
	var in_use bool
	err := row.Scan(&in_use)
	return in_use, err
}

const hasLivePlannedPaymentsForCategory = `-- name: HasLivePlannedPaymentsForCategory :one
SELECT EXISTS(
    SELECT 1
    FROM planned_payments
    WHERE user_id = $1 AND deleted_at IS NULL AND category_id = $2
) AS in_use
`

type HasLivePlannedPaymentsForCategoryParams struct {
	UserID     uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) HasLivePlannedPaymentsForCategory(ctx context.Context, arg HasLivePlannedPaymentsForCategoryParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasLivePlannedPaymentsForCategory, arg.UserID, arg.CategoryID)
	var in_use bool
	err := row.Scan(&in_use)
	return in_use, err
}

const softDeletePlannedPayment = `-- name: SoftDeletePlannedPayment :one
UPDATE planned_payments
SET deleted_at = now(), version = version + 1, updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING version
`

type SoftDeletePlannedPaymentParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) SoftDeletePlannedPayment(ctx context.Context, arg SoftDeletePlannedPaymentParams) (int32, error) {
	row := q.db.QueryRow(ctx, softDeletePlannedPayment, arg.ID, arg.UserID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const syncPlannedPaymentsByIDs = `-- name: SyncPlannedPaymentsByIDs :many
SELECT id, user_id, type, amount, name, account_id, category_id,
       next_due, anchor_date, regularity, confirm_mode, reminder, note,
       version, deleted_at
FROM planned_payments
WHERE user_id = $1 AND id = ANY($2::uuid[])
`

type SyncPlannedPaymentsByIDsParams struct {
	UserID uuid.UUID
	Ids    []uuid.UUID
}

type SyncPlannedPaymentsByIDsRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Type        string
	Amount      int64
	Name        string
	AccountID   uuid.UUID
	CategoryID  uuid.UUID
	NextDue     time.Time
	AnchorDate  time.Time
	Regularity  string
	ConfirmMode string
	Reminder    string
	Note        string
	Version     int32
	DeletedAt   *time.Time
}

func (q *Queries) SyncPlannedPaymentsByIDs(ctx context.Context, arg SyncPlannedPaymentsByIDsParams) ([]SyncPlannedPaymentsByIDsRow, error) {
	rows, err := q.db.Query(ctx, syncPlannedPaymentsByIDs, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncPlannedPaymentsByIDsRow
	for rows.Next() {
		var i SyncPlannedPaymentsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Amount,
			&i.Name,
			&i.AccountID,
			&i.CategoryID,
			&i.NextDue,
			&i.AnchorDate,
			&i.Regularity,
			&i.ConfirmMode,
			&i.Reminder,
			&i.Note,
			&i.Version,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncReplacePlannedPayment = `-- name: SyncReplacePlannedPayment :one
UPDATE planned_payments
SET
    type         = $1,
    amount       = $2,
    name         = $3,
    account_id   = $4,
    category_id  = $5,
    next_due     = $6,
    anchor_date  = $7,
    regularity   = $8,
    confirm_mode = $9,
    reminder     = $10,
    note         = $11,
    version      = version + 1,
    updated_at   = now()
WHERE id = $12 AND user_id = $13 AND deleted_at IS NULL AND version = $14
RETURNING id, user_id, type, amount, name, account_id, category_id,
          next_due, anchor_date, regularity, confirm_mode, reminder, note,
          created_at, updated_at, version
`

type SyncReplacePlannedPaymentParams struct {
	Type        string
	Amount      int64
	Name        string
	AccountID   uuid.UUID
	CategoryID  uuid.UUID
	NextDue     time.Time
	AnchorDate  time.Time
	Regularity  string
	ConfirmMode string
	Reminder    string
	Note        string
	ID          uuid.UUID
	UserID      uuid.UUID
	BaseVersion int32
}

type SyncReplacePlannedPaymentRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Type        string
	Amount      int64
	Name        string
	AccountID   uuid.UUID
	CategoryID  uuid.UUID
	NextDue     time.Time
	AnchorDate  time.Time
	Regularity  string
	ConfirmMode string
	Reminder    string
	Note        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Version     int32
}

// Full-state CAS upsert from a sync push.
func (q *Queries) SyncReplacePlannedPayment(ctx context.Context, arg SyncReplacePlannedPaymentParams) (SyncReplacePlannedPaymentRow, error) {
	row := q.db.QueryRow(ctx, syncReplacePlannedPayment,
		arg.Type,
		arg.Amount,
		arg.Name,
		arg.AccountID,
		arg.CategoryID,
		arg.NextDue,
		arg.AnchorDate,
		arg.Regularity,
		arg.ConfirmMode,
		arg.Reminder,
		arg.Note,
		arg.ID,
		arg.UserID,
		arg.BaseVersion,
	)
	var i SyncReplacePlannedPaymentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Name,
		&i.AccountID,
		&i.CategoryID,
		&i.NextDue,
		&i.AnchorDate,
		&i.Regularity,
		&i.ConfirmMode,
		&i.Reminder,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updatePlannedPayment = `-- name: UpdatePlannedPayment :one
UPDATE planned_payments
SET
    amount       = COALESCE($1, amount),
    name         = COALESCE($2, name),
    note         = COALESCE($3, note),
    account_id   = COALESCE($4, account_id),
    category_id  = COALESCE($5, category_id),
    next_due     = COALESCE($6, next_due),
    anchor_date  = COALESCE($6, anchor_date),
    regularity   = COALESCE($7, regularity),
    confirm_mode = COALESCE($8, confirm_mode),
    reminder     = COALESCE($9, reminder),
    version      = version + 1,
    updated_at   = now()
WHERE id = $10 AND user_id = $11 AND deleted_at IS NULL AND version = $12
RETURNING id, user_id, type, amount, name, account_id, category_id,
          next_due, anchor_date, regularity, confirm_mode, reminder, note,
          created_at, updated_at, version
`

type UpdatePlannedPaymentParams struct {
	Amount      *int64
	Name        *string
	Note        *string
	AccountID   *uuid.UUID
	CategoryID  *uuid.UUID
	NextDue     *time.Time
	Regularity  *string
	ConfirmMode *string
	Reminder    *string
	ID          uuid.UUID
	UserID      uuid.UUID
	Version     int32
}

type UpdatePlannedPaymentRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Type        string
	Amount      int64
	Name        string
	AccountID   uuid.UUID
	CategoryID  uuid.UUID
	NextDue     time.Time
	AnchorDate  time.Time
	Regularity  string
	ConfirmMode string
	Reminder    string
	Note        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Version     int32
}

// Optimistic concurrency: the WHERE clause includes version = @version (and
// liveness) so a concurrent update yields zero rows. PATCH fields use
// COALESCE for nil = keep; a non-nil empty name/note clears it. Changing
// next_due resets the anchor to the same new date.
func (q *Queries) UpdatePlannedPayment(ctx context.Context, arg UpdatePlannedPaymentParams) (UpdatePlannedPaymentRow, error) {
	row := q.db.QueryRow(ctx, updatePlannedPayment,
		arg.Amount,
		arg.Name,
		arg.Note,
		arg.AccountID,
		arg.CategoryID,
		arg.NextDue,
		arg.Regularity,
		arg.ConfirmMode,
		arg.Reminder,
		arg.ID,
		arg.UserID,
		arg.Version,
	)
	var i UpdatePlannedPaymentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Name,
		&i.AccountID,
		&i.CategoryID,
		&i.NextDue,
		&i.AnchorDate,
		&i.Regularity,
		&i.ConfirmMode,
		&i.Reminder,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const usersWithDueAutoPlannedPayments = `-- name: UsersWithDueAutoPlannedPayments :many
SELECT DISTINCT user_id
FROM planned_payments
WHERE deleted_at IS NULL
  AND confirm_mode = 'auto'
  AND next_due <= $1
`

// Users owning at least one due auto plan (the job's per-user work list).
func (q *Queries) UsersWithDueAutoPlannedPayments(ctx context.Context, today time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, usersWithDueAutoPlannedPayments, today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
