// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// accounts. Every query scopes by user_id (IDOR-safe: a cross-user access
	// returns "not found", never the row). Balance is computed via the
	// account_contributions view (opening + manual + sum(signed)).
	CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error)
	// categories (per-user, unique name within user). Scoped by user_id everywhere.
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	// idempotency keys (POST /api/transactions idempotency cache).
	// user_id is a uuid; the idempotency_key value is a client string.
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error)
	// sessions (stateful auth). id is a hex token, NOT a uuid.
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// transactions. Scoped by user_id everywhere (IDOR protection).
	//
	// The keyset-cursor index transactions(user_id, occurred_at DESC, id DESC)
	// serves ListTransactions directly.
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	DeleteAccount(ctx context.Context, arg DeleteAccountParams) (int64, error)
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error)
	DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteIdempotencyKey(ctx context.Context, arg DeleteIdempotencyKeyParams) (int64, error)
	DeleteSession(ctx context.Context, id string) (int64, error)
	DeleteSessionsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	DeleteSessionsByUserExcept(ctx context.Context, arg DeleteSessionsByUserExceptParams) (int64, error)
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error)
	ExtendSession(ctx context.Context, arg ExtendSessionParams) (int64, error)
	GetAccount(ctx context.Context, arg GetAccountParams) (GetAccountRow, error)
	GetAccountBalances(ctx context.Context, userID uuid.UUID) ([]GetAccountBalancesRow, error)
	GetAccounts(ctx context.Context, userID uuid.UUID) ([]GetAccountsRow, error)
	GetCategories(ctx context.Context, arg GetCategoriesParams) ([]Category, error)
	GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error)
	GetIdempotencyByUserAndKey(ctx context.Context, arg GetIdempotencyByUserAndKeyParams) (IdempotencyKey, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetSessionsByUser(ctx context.Context, userID uuid.UUID) ([]Session, error)
	GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error)
	// users
	//
	// Note: user_id scoping is not needed on the user table itself (the PK is the
	// identity). All resource tables (accounts/categories/transactions/sessions/...)
	// scope every query by user_id (IDOR protection - see their query files).
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	LatestPasswordResetTokenAgeSeconds(ctx context.Context, userID uuid.UUID) (int32, error)
	// email verification + password reset throttling helpers.
	// Each returns the age in seconds of the most recently issued code/token for a
	// user, or no rows when none exists (the repository maps that to "no active").
	LatestVerificationCodeAgeSeconds(ctx context.Context, userID uuid.UUID) (int32, error)
	// Keyset cursor pagination (occurred_at DESC, id DESC). Each optional filter is
	// applied only when its narg is non-NULL. The account filter matches a
	// transaction if ANY of its account refs (account_id / from / to) equals it,
	// preserving the original OR-across-refs semantics.
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	SetEmailVerified(ctx context.Context, id uuid.UUID) (int64, error)
	// COALESCE keeps a column unchanged when its narg is NULL (PATCH semantics).
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (UpdateAccountRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateIdempotencyKey(ctx context.Context, arg UpdateIdempotencyKeyParams) (IdempotencyKey, error)
	// Optimistic concurrency: the WHERE clause includes version = @version so a
	// concurrent update yields zero rows (-> not found / version conflict).
	// version is incremented atomically; PATCH fields use COALESCE for nil = keep.
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
