// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package db

import (
	"context"
	"time"
)

const deleteTombstonedAccountsBefore = `-- name: DeleteTombstonedAccountsBefore :execrows
DELETE FROM accounts
WHERE deleted_at IS NOT NULL AND deleted_at < $1
`

func (q *Queries) DeleteTombstonedAccountsBefore(ctx context.Context, deletedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTombstonedAccountsBefore, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTombstonedCategoriesBefore = `-- name: DeleteTombstonedCategoriesBefore :execrows
DELETE FROM categories
WHERE deleted_at IS NOT NULL AND deleted_at < $1
`

func (q *Queries) DeleteTombstonedCategoriesBefore(ctx context.Context, deletedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTombstonedCategoriesBefore, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTombstonedTransactionsBefore = `-- name: DeleteTombstonedTransactionsBefore :execrows

DELETE FROM transactions
WHERE deleted_at IS NOT NULL AND deleted_at < $1
`

// Tombstone retention: hard-delete rows that have been soft-deleted longer
// than the retention window. change_log entries are kept on purpose - pulls
// serve tombstones from the log alone, so devices offline during the window
// still converge to the deleted state. Transactions go first: their FKs
// reference accounts/categories, so those rows can only go once no
// tombstoned transaction still points at them.
func (q *Queries) DeleteTombstonedTransactionsBefore(ctx context.Context, deletedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTombstonedTransactionsBefore, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
