// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (id, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, expires_at, created_at, updated_at
`

type CreateSessionParams struct {
	ID        string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

// sessions (stateful auth). id is a hex token, NOT a uuid.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionsByUser = `-- name: DeleteSessionsByUser :execrows
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionsByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionsByUserExcept = `-- name: DeleteSessionsByUserExcept :execrows
DELETE FROM sessions WHERE user_id = $1 AND id <> $2
`

type DeleteSessionsByUserExceptParams struct {
	UserID uuid.UUID
	ID     string
}

func (q *Queries) DeleteSessionsByUserExcept(ctx context.Context, arg DeleteSessionsByUserExceptParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionsByUserExcept, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extendSession = `-- name: ExtendSession :execrows
UPDATE sessions
SET expires_at = $2,
    updated_at = now()
WHERE id = $1 AND expires_at > now()
`

type ExtendSessionParams struct {
	ID        string
	ExpiresAt time.Time
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendSession, arg.ID, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, expires_at, created_at, updated_at
FROM sessions
WHERE id = $1 AND expires_at > now()
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionsByUser = `-- name: GetSessionsByUser :many
SELECT id, user_id, expires_at, created_at, updated_at
FROM sessions
WHERE user_id = $1 AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) GetSessionsByUser(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
