// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO transactions (
    user_id, type, amount, description, occurred_at,
    account_id, category_id, from_account_id, to_account_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
    id, user_id, type, amount, description, occurred_at,
    created_at, updated_at, version,
    account_id, category_id, from_account_id, to_account_id
`

type CreateTransactionParams struct {
	UserID        uuid.UUID
	Type          string
	Amount        int64
	Description   string
	OccurredAt    time.Time
	AccountID     *uuid.UUID
	CategoryID    *uuid.UUID
	FromAccountID *uuid.UUID
	ToAccountID   *uuid.UUID
}

// transactions. Scoped by user_id everywhere (IDOR protection).
//
// The keyset-cursor index transactions(user_id, occurred_at DESC, id DESC)
// serves ListTransactions directly.
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Type,
		arg.Amount,
		arg.Description,
		arg.OccurredAt,
		arg.AccountID,
		arg.CategoryID,
		arg.FromAccountID,
		arg.ToAccountID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.AccountID,
		&i.CategoryID,
		&i.FromAccountID,
		&i.ToAccountID,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTransaction = `-- name: GetTransaction :one
SELECT
    id, user_id, type, amount, description, occurred_at,
    created_at, updated_at, version,
    account_id, category_id, from_account_id, to_account_id
FROM transactions
WHERE id = $1 AND user_id = $2
`

type GetTransactionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.AccountID,
		&i.CategoryID,
		&i.FromAccountID,
		&i.ToAccountID,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT
    id, user_id, type, amount, description, occurred_at,
    created_at, updated_at, version,
    account_id, category_id, from_account_id, to_account_id
FROM transactions
WHERE
    user_id = $1
    AND ($2::text IS NULL OR type = $2)
    AND (
        $3::uuid IS NULL
        OR account_id = $3
        OR from_account_id = $3
        OR to_account_id = $3
    )
    AND ($4::uuid IS NULL OR category_id = $4)
    AND ($5::timestamptz IS NULL OR occurred_at >= $5)
    AND ($6::timestamptz IS NULL OR occurred_at <= $6)
    AND (
        $7::timestamptz IS NULL
        OR occurred_at < $7
        OR (occurred_at = $7 AND id < $8)
    )
ORDER BY occurred_at DESC, id DESC
LIMIT $9
`

type ListTransactionsParams struct {
	UserID           uuid.UUID
	Type             *string
	AccountID        *uuid.UUID
	CategoryID       *uuid.UUID
	FromDate         *time.Time
	ToDate           *time.Time
	CursorOccurredAt *time.Time
	CursorID         *uuid.UUID
	Limit            int32
}

// Keyset cursor pagination (occurred_at DESC, id DESC). Each optional filter is
// applied only when its narg is non-NULL. The account filter matches a
// transaction if ANY of its account refs (account_id / from / to) equals it,
// preserving the original OR-across-refs semantics.
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.UserID,
		arg.Type,
		arg.AccountID,
		arg.CategoryID,
		arg.FromDate,
		arg.ToDate,
		arg.CursorOccurredAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.AccountID,
			&i.CategoryID,
			&i.FromAccountID,
			&i.ToAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET
    amount           = COALESCE($1, amount),
    description      = COALESCE($2, description),
    occurred_at      = COALESCE($3, occurred_at),
    account_id       = COALESCE($4, account_id),
    category_id      = COALESCE($5, category_id),
    from_account_id  = COALESCE($6, from_account_id),
    to_account_id    = COALESCE($7, to_account_id),
    version          = version + 1,
    updated_at       = now()
WHERE id = $8 AND user_id = $9 AND version = $10
RETURNING
    id, user_id, type, amount, description, occurred_at,
    created_at, updated_at, version,
    account_id, category_id, from_account_id, to_account_id
`

type UpdateTransactionParams struct {
	Amount        *int64
	Description   *string
	OccurredAt    *time.Time
	AccountID     *uuid.UUID
	CategoryID    *uuid.UUID
	FromAccountID *uuid.UUID
	ToAccountID   *uuid.UUID
	ID            uuid.UUID
	UserID        uuid.UUID
	Version       int32
}

// Optimistic concurrency: the WHERE clause includes version = @version so a
// concurrent update yields zero rows (-> not found / version conflict).
// version is incremented atomically; PATCH fields use COALESCE for nil = keep.
func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.Amount,
		arg.Description,
		arg.OccurredAt,
		arg.AccountID,
		arg.CategoryID,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.ID,
		arg.UserID,
		arg.Version,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.AccountID,
		&i.CategoryID,
		&i.FromAccountID,
		&i.ToAccountID,
	)
	return i, err
}
