// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT
    id,
    email,
    password_hash,
    (email_verified_at IS NOT NULL)::boolean AS email_verified,
    display_name,
    created_at,
    updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID            uuid.UUID
	Email         string
	PasswordHash  string
	EmailVerified bool
	DisplayName   *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// users
//
// Note: scoping is not needed on the user table itself (the PK is the
// identity). All resource tables scope every query by household_id (IDOR
// protection - see their query files).
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    email,
    '' AS password_hash,
    (email_verified_at IS NOT NULL)::boolean AS email_verified,
    display_name,
    created_at,
    updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID            uuid.UUID
	Email         string
	PasswordHash  string
	EmailVerified bool
	DisplayName   *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE users
SET display_name = $2,
    updated_at   = now()
WHERE id = $1
RETURNING
    id,
    email,
    (email_verified_at IS NOT NULL)::boolean AS email_verified,
    display_name,
    created_at,
    updated_at
`

type UpdateUserDisplayNameParams struct {
	ID          uuid.UUID
	DisplayName *string
}

type UpdateUserDisplayNameRow struct {
	ID            uuid.UUID
	Email         string
	EmailVerified bool
	DisplayName   *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Profile edit: sets the member-facing display name. Non-empty trimmed and
// length-capped by the service layer before it gets here.
func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (UpdateUserDisplayNameRow, error) {
	row := q.db.QueryRow(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	var i UpdateUserDisplayNameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
